{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Measure\",\"dCalendar\",\"assignment_groups_list\",\"Sample File (4)\",\"Parameter4\",\"Transform Sample File (4)\",\"Transform File (4)\",\"analyst_list\",\"Sample File (5)\",\"Parameter5\",\"Transform Sample File (5)\",\"Transform File (5)\",\"F_main\",\"Sample File (6)\",\"Parameter6\",\"Transform Sample File (6)\",\"Transform File (6)\",\"Sample File (7)\",\"Parameter7\",\"Transform Sample File (7)\",\"Transform File (7)\",\"Sample File (8)\",\"Parameter8\",\"Transform Sample File (8)\",\"Transform File (8)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1452.0 (24.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Sample File (4)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let\r",
          "    Source = AzureStorage.DataLake(\"https://hyperautoadlsanlprod.dfs.core.windows.net/gold/parameters/internal_assignment_groups_list\"),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Extension] = \".parquet\")),\r",
          "    Navigation1 = #\"Filtered Rows\"{0}[Content]\r",
          "in\r",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "083b87ad-aad0-4265-9d13-c3fa18af43b8",
        "queryGroup": "Transform File from Query1 (3)\\Helper Queries"
      },
      {
        "name": "Parameter4",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (4)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (4)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "7fcb5f77-31b2-4781-abaa-a5ca0ccea650",
        "queryGroup": "Transform File from Query1 (3)\\Helper Queries"
      },
      {
        "name": "Transform Sample File (4)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Parquet.Document(Parameter4, [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "362bbf63-1c0d-4254-a522-49b45c93d4a4",
        "queryGroup": "Transform File from Query1 (3)"
      },
      {
        "name": "Transform File (4)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let\r",
          "    Source = (Parameter4 as binary) => let\r",
          "        Source = Parquet.Document(Parameter4, [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])\r",
          "    in\r",
          "        Source\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "f5bc6349-a8de-4852-8fe6-a29966772423",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File (4)\"\"}\" ]",
        "queryGroup": "Transform File from Query1 (3)\\Helper Queries"
      },
      {
        "name": "Sample File (5)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let\r",
          "    Source = AzureStorage.DataLake(\"https://hyperautoadlsanlprod.dfs.core.windows.net/gold/parameters/internal_analyst_list\"),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Extension] = \".parquet\")),\r",
          "    Navigation1 = #\"Filtered Rows\"{0}[Content]\r",
          "in\r",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "6a7c27fc-0c71-40a8-8c58-bda30c8b4b43",
        "queryGroup": "Transform File from Query1 (4)\\Helper Queries"
      },
      {
        "name": "Parameter5",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (5)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (5)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "22b01dcc-7db8-4beb-a2ec-40f8c5175f5b",
        "queryGroup": "Transform File from Query1 (4)\\Helper Queries"
      },
      {
        "name": "Transform Sample File (5)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Parquet.Document(Parameter5, [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "8b998783-8a90-4c21-8e6f-638185b43a5d",
        "queryGroup": "Transform File from Query1 (4)"
      },
      {
        "name": "Transform File (5)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let\r",
          "    Source = (Parameter5 as binary) => let\r",
          "        Source = Parquet.Document(Parameter5, [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])\r",
          "    in\r",
          "        Source\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "9a4968a8-193b-4c69-bebd-3a7c724170ea",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File (5)\"\"}\" ]",
        "queryGroup": "Transform File from Query1 (4)\\Helper Queries"
      },
      {
        "name": "Sample File (6)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let\r",
          "    Source = AzureStorage.DataLake(\"https://hyperautoadlsanlprod.dfs.core.windows.net/gold/schemas/ams/main\"),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Extension] = \".parquet\")),\r",
          "    Navigation1 = #\"Filtered Rows\"{0}[Content]\r",
          "in\r",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "d99c901d-7afa-4bfd-aad7-2af43c66e54f",
        "queryGroup": "Transform File from Query1 (5)\\Helper Queries"
      },
      {
        "name": "Parameter6",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (6)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (6)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "41fcd48f-5da3-4b78-b851-92de47951ed7",
        "queryGroup": "Transform File from Query1 (5)\\Helper Queries"
      },
      {
        "name": "Transform Sample File (6)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Parquet.Document(Parameter6, [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "04c9f552-305a-4823-82b5-1dbab0f907dc",
        "queryGroup": "Transform File from Query1 (5)"
      },
      {
        "name": "Transform File (6)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let\r",
          "    Source = (Parameter6 as binary) => let\r",
          "        Source = Parquet.Document(Parameter6, [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])\r",
          "    in\r",
          "        Source\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "88d78313-ab16-4e1a-9670-8e1e05b48e81",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File (6)\"\"}\" ]",
        "queryGroup": "Transform File from Query1 (5)\\Helper Queries"
      },
      {
        "name": "Sample File (7)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let\r",
          "    Source = AzureStorage.DataLake(\"https://hyperautoadlsanlprod.dfs.core.windows.net/gold/parameters/internal_analyst_list\"),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Extension] = \".parquet\")),\r",
          "    Navigation1 = #\"Filtered Rows\"{0}[Content]\r",
          "in\r",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "6c88cb29-3a9c-4c36-beec-e1c82bf90567",
        "queryGroup": "Transform File from Query1 (6)\\Helper Queries"
      },
      {
        "name": "Parameter7",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (7)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (7)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "03f782b7-0d2e-4f0d-affe-585013e556fd",
        "queryGroup": "Transform File from Query1 (6)\\Helper Queries"
      },
      {
        "name": "Transform Sample File (7)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Parquet.Document(Parameter7, [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "59f956b8-1ea3-42f3-9347-39ac8747d6b6",
        "queryGroup": "Transform File from Query1 (6)"
      },
      {
        "name": "Transform File (7)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let\r",
          "    Source = (Parameter7 as binary) => let\r",
          "        Source = Parquet.Document(Parameter7, [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])\r",
          "    in\r",
          "        Source\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "f37b7267-3cf5-4a14-8f20-87bc33fee373",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File (7)\"\"}\" ]",
        "queryGroup": "Transform File from Query1 (6)\\Helper Queries"
      },
      {
        "name": "Sample File (8)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let\r",
          "    Source = AzureStorage.DataLake(\"https://hyperautoadlsanlprod.dfs.core.windows.net/gold/parameters/internal_analyst_list\"),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Extension] = \".parquet\")),\r",
          "    Navigation1 = #\"Filtered Rows\"{0}[Content]\r",
          "in\r",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "6629f476-d2c8-4c5d-bd73-e6c7f9fa801b",
        "queryGroup": "Transform File from analyst_list\\Helper Queries"
      },
      {
        "name": "Parameter8",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (8)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (8)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "b033e359-bf00-4e15-bce5-98e3666cafb9",
        "queryGroup": "Transform File from analyst_list\\Helper Queries"
      },
      {
        "name": "Transform Sample File (8)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Parquet.Document(Parameter8, [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "b04ca36a-a318-4bcb-99e8-da37ed0dd9af",
        "queryGroup": "Transform File from analyst_list"
      },
      {
        "name": "Transform File (8)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let\r",
          "    Source = (Parameter8 as binary) => let\r",
          "        Source = Parquet.Document(Parameter8, [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])\r",
          "    in\r",
          "        Source\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "2e235226-ee50-4f50-8f97-9c18c6846f93",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File (8)\"\"}\" ]",
        "queryGroup": "Transform File from analyst_list\\Helper Queries"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Query1"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Transform File from Query2"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "Transform File from Query1 (2)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "6"
          }
        ],
        "folder": "Transform File from Query1 (3)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Query1 (3)\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "8"
          }
        ],
        "folder": "Transform File from Query1 (4)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Query1 (4)\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "10"
          }
        ],
        "folder": "Transform File from Query1 (5)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Query1 (5)\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "12"
          }
        ],
        "folder": "Transform File from Query1 (6)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Query1 (6)\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "14"
          }
        ],
        "folder": "Transform File from analyst_list"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from analyst_list\\Helper Queries"
      }
    ],
    "relationships": [
      {
        "name": "b38a4e8c-9194-49b6-8170-c7e6666fffff",
        "fromColumn": "Data",
        "fromTable": "dCalendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_72c50f6a-e7cb-4a53-a5fa-5ecc7c7655c4"
      },
      {
        "name": "eb981103-134e-4908-8bf9-96b687d87df4",
        "fromColumn": "opened_at",
        "fromTable": "F_main",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2f6c9ccd-1390-4791-9967-d365da8e8579"
      },
      {
        "name": "fd25827f-281d-4ac6-9c42-f9794f044c0e",
        "fromColumn": "resolved_at",
        "fromTable": "F_main",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_81c838cd-46d2-4463-91c0-f6ee98a86607"
      },
      {
        "name": "a02935db-7267-4f41-b35a-619651e74328",
        "fromColumn": "closed_at",
        "fromTable": "F_main",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_15fca2cf-8a52-4f21-bcee-9c358a8334bf"
      },
      {
        "name": "a5dc6bd2-8ee8-4584-80c0-7d001ff15c96",
        "fromColumn": "sys_updated_on_inc",
        "fromTable": "F_main",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_640ae0a0-c358-482d-be4b-aaee15fb27e9"
      },
      {
        "name": "ff765e2a-2243-4313-b8ca-a573d152e3e2",
        "fromColumn": "sys_updated_on_formated_inc",
        "fromTable": "F_main",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ff4037a4-71bd-4c0f-9e70-eda722c4953b"
      },
      {
        "name": "AutoDetected_8f2a83ba-845b-4ed7-886a-6645b41ca47a",
        "fromColumn": "assignment_groups_list.title",
        "fromTable": "F_main",
        "toColumn": "title",
        "toTable": "assignment_groups_list"
      },
      {
        "name": "e09be9b1-65f1-bc8b-d8a0-6a647360f230",
        "fromColumn": "opened_at_formated",
        "fromTable": "F_main",
        "toColumn": "Data",
        "toTable": "dCalendar"
      },
      {
        "name": "85806b80-16bc-1e49-d157-c5e9649eb214",
        "fromColumn": "resolved_at_formated",
        "fromTable": "F_main",
        "isActive": false,
        "toColumn": "Data",
        "toTable": "dCalendar"
      },
      {
        "name": "65373ed4-d262-67bb-176e-0af515d03bfb",
        "fromColumn": "closed_at_formated",
        "fromTable": "F_main",
        "isActive": false,
        "toColumn": "Data",
        "toTable": "dCalendar"
      },
      {
        "name": "bba18602-6b83-2936-b4a7-39a780276430",
        "fromColumn": "assigned_to_sys_id",
        "fromTable": "F_main",
        "toColumn": "sys_id",
        "toTable": "analyst_list"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_4685656d-87d2-4def-8c7d-415d639c3c35",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "83f80894-56fb-49a6-b111-0da9b3c13c1c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "09498c6c-e63f-45fc-bd15-6df9c38af290",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "1bff670a-f23d-4dbd-8edc-7a94c292cd88",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "db21d168-45fc-499c-93d2-ed85b18fdabb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "94e8b8cd-c75f-45ec-af29-c705b188c0fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "cf9cb1c1-056c-4046-852b-9a1c72f7de54",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "211cfab6-92e7-492e-9445-7a5ab61406c2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "31ff3bbf-7948-4739-af88-d9cb0f080cc6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "66db5317-f85f-4846-9838-caf53f678928",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "aa517e38-d72b-46f3-b96e-7d981c82a531",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "86f2414c-62b1-4093-a20b-68ea32bc01d0",
                "ordinal": 3
              }
            ],
            "lineageTag": "b989d8fa-55f8-4bc0-b224-55fec76253d3"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "ccea6111-83e3-4f17-a1b0-ba359e6bf1b1",
        "partitions": [
          {
            "name": "DateTableTemplate_4685656d-87d2-4def-8c7d-415d639c3c35",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Measure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "lineageTag": "ce193596-554a-4e3b-83c4-e61552fd220f",
        "measures": [
          {
            "name": "Count - SLA not Breached",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "sum(F_main[sla_internal_count]) - [Count - SLA Breached]"
            ],
            "formatString": "0",
            "lineageTag": "e8dddd44-a1db-46a4-9b5c-7fd2bbfdd256"
          },
          {
            "name": "% SLA Achievement",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "IF([Resolved Tickets]>0,  -- Evita mostrar SLA de quem no teve ticket resolvido",
              "CALCULATE(",
              "1 - DIVIDE(",
              "    sum(F_main[sla_breached_internal]),",
              "    sum(F_main[sla_internal_count]),0)",
              "    ,",
              "    USERELATIONSHIP(dCalendar[Data],F_main[resolved_at_formated])) -- retorna com base na data de resolved",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1b7fa599-9478-41a3-97be-f715c4237ffb"
          },
          {
            "name": "Total Tickets",
            "displayFolder": "Volume of Tickets",
            "expression": "DISTINCTCOUNT(metric[Number])",
            "formatString": "0",
            "lineageTag": "d46e7628-2d57-4e02-b04c-38a6391f5d85"
          },
          {
            "name": "% SLA Breached/Total",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "DIVIDE(",
              "    [Count - SLA not Breached],",
              "    CALCULATE(",
              "        [Total Tickets],",
              "        ALL(metric[Check - Breached SLA])",
              "    ))"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "3840aebc-80c9-46d2-9252-055825e5ca89"
          },
          {
            "name": "P3 Tickets",
            "displayFolder": "Priority",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Tickets],",
              "    'metric'[Priority] = \"3 - Moderate\")"
            ],
            "formatString": "0",
            "lineageTag": "cec175e3-cbd1-4f9c-9d35-2d6b8b831a96"
          },
          {
            "name": "P2 Tickets",
            "displayFolder": "Priority",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Tickets],",
              "    'metric'[Priority] = \"2 - High\")"
            ],
            "formatString": "0",
            "lineageTag": "6de7533b-7f96-4911-9912-ada68a0940a1"
          },
          {
            "name": "P2 Tickets SLA Breached",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Priority",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(metric[Number]),",
              "    metric[breached_sla]>0,",
              "    metric[Priority] = \"2 - High\")"
            ],
            "lineageTag": "e1c72762-1851-44d8-a461-fed7893ffef4"
          },
          {
            "name": "P3 Tickets SLA Breached",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Priority",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(metric[Number]),",
              "    metric[breached_sla]>0,",
              "    metric[Priority] = \"3 - Moderate\")"
            ],
            "lineageTag": "4d3b3463-a9c3-49e7-88e7-0b5a43d65172"
          },
          {
            "name": "%P2 SLA Breached",
            "displayFolder": "Priority",
            "expression": [
              "",
              "DIVIDE([P2 Tickets SLA Breached],[P2 Tickets])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "afc016c2-9104-491e-a56c-865115a12507"
          },
          {
            "name": "%P3 SLA Breached",
            "displayFolder": "Priority",
            "expression": [
              "",
              "DIVIDE([P3 Tickets SLA Breached],[P3 Tickets])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "302ec161-2d29-4df7-b4d5-b2a3d11914d6"
          },
          {
            "name": "P4 Tickets SLA Breached",
            "displayFolder": "Priority",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(metric[Number]),",
              "    metric[breached_sla]>0,",
              "    metric[Priority] = \"4 - Low\")"
            ],
            "formatString": "0",
            "lineageTag": "f88fa14a-5cb5-485d-bc57-75ca2e82d068"
          },
          {
            "name": "P4 Tickets",
            "displayFolder": "Priority",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Tickets],",
              "    'metric'[Priority] = \"4 - Low\")"
            ],
            "formatString": "0",
            "lineageTag": "4b2f9a5d-b79e-4be0-875b-d31e8162e522"
          },
          {
            "name": "%P4 SLA Breached",
            "displayFolder": "Priority",
            "expression": [
              "",
              "DIVIDE([P4 Tickets SLA Breached],[P4 Tickets])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "85ef13eb-143a-4ad4-8eb4-11dfcd8834b4"
          },
          {
            "name": "P1 Tickets",
            "displayFolder": "Priority",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Tickets],",
              "    'metric'[Priority] = \"1 - High\")"
            ],
            "formatString": "0",
            "lineageTag": "304b2f30-9a41-4518-8e91-bbb7e9ec1e59"
          },
          {
            "name": "P1 Tickets SLA Breached",
            "displayFolder": "Priority",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(metric[Number]),",
              "    metric[breached_sla]>0,",
              "    metric[Priority] = \"1 - High\")"
            ],
            "formatString": "0",
            "lineageTag": "a0b9d6ee-ff32-4fda-90f8-dd6a7892f913"
          },
          {
            "name": "%P1 SLA Breached",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Priority",
            "expression": [
              "",
              "DIVIDE([P1 Tickets SLA Breached],[P1 Tickets])"
            ],
            "lineageTag": "1bbdbcf0-d2a3-4773-ba3d-a58f75f48476"
          },
          {
            "name": "Last Month - Total Tickets",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "CALCULATE(",
              "   [Resolved Tickets],dCalendar[Check_Relative Period]=TRUE(),DATEADD(dCalendar[Data],-1,MONTH))"
            ],
            "formatString": "0",
            "lineageTag": "5fe06b3f-296b-45f5-bdb9-c06a28717af8"
          },
          {
            "name": "Last Month - Count SLA not Breached",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "CALCULATE(",
              "    sum(F_main[sla_internal_count]),",
              "    dCalendar[Check_Relative Period]=TRUE(),",
              "    DATEADD(dCalendar[Data],-1,MONTH)) ",
              "    -",
              "    [Last Month Count SLA Breached]"
            ],
            "formatString": "0",
            "lineageTag": "013986f7-b592-4ca2-a166-04676ee21f36"
          },
          {
            "name": "% Last Month - SLA Achievement",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "IF([Last Month - Total Tickets] >0,",
              "1 - DIVIDE(",
              "    [Last Month Count SLA Breached],",
              "    [Last Month n SLA]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5ff8a584-5c50-488a-9bf3-f3117c0487a4"
          },
          {
            "name": "Count Analysts",
            "displayFolder": "Ticket Rate",
            "expression": "CALCULATE(DISTINCTCOUNT(metric[Resource Name]),ALL(dCalendar[Week/Month]))",
            "formatString": "0",
            "lineageTag": "fae67442-2c6d-4c89-b3a0-e4abcc9c77c1"
          },
          {
            "name": "Opening Rate",
            "displayFolder": "Ticket Rate",
            "expression": "(DIVIDE([Opened Tickets],[Count Analysts]))",
            "formatString": "0.0",
            "lineageTag": "d4e0b7fa-7866-4e57-9068-ff6b2f78fbe5"
          },
          {
            "name": "Closing Rate",
            "displayFolder": "Ticket Rate",
            "expression": "DIVIDE([Total Tickets],[Count Analysts])",
            "formatString": "0.0",
            "lineageTag": "f9bf828f-9c1c-4b2d-a3a3-330fa597ea4f"
          },
          {
            "name": "Count - SLA Breached",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('F_main'[sla_breached_internal]),",
              "    'F_main'[sla_breached_internal] >0,",
              "    USERELATIONSHIP(dCalendar[Data],F_main[resolved_at_formated]))"
            ],
            "formatString": "0",
            "lineageTag": "7a30782c-3f5b-449b-aa17-915b47de40c0"
          },
          {
            "name": "Resolved Tickets",
            "displayFolder": "Ticket Rate",
            "expression": [
              "",
              "CALCULATE(",
              "    [Opened Tickets],",
              "    USERELATIONSHIP(dCalendar[Data],F_main[resolved_at_formated]))"
            ],
            "formatString": "0",
            "lineageTag": "bed15ede-03ad-48a1-9e3b-445a309e4b13"
          },
          {
            "name": "Resolved Rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Ticket Rate",
            "expression": "(DIVIDE([Resolved Tickets],[Count Analysts]))",
            "lineageTag": "204abf9e-0a66-4c83-80a6-db7cf85979d9"
          },
          {
            "name": "% SLA Actual/Previous",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "IF([Resolved Tickets]>0 && [Last Month - Total Tickets]>0,[% SLA Achievement] - [% Last Month - SLA Achievement])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "45d1e35f-38d7-4d68-8216-dca81be90442"
          },
          {
            "name": "Rank Skill %SLA Growth",
            "description": "Ranking",
            "displayFolder": "Ranking SLA Comp.",
            "expression": [
              "",
              "SWITCH(",
              "    [Order Type],",
              "    \"Ascending\", ",
              "        RANKX(",
              "            ALL(metric[Skill]),",
              "            [% SLA Actual/Previous],",
              "            ,",
              "            ASC,",
              "            DENSE",
              "        ),",
              "    \"Descending\",",
              "        RANKX(",
              "            ALL(metric[Skill]),",
              "            [% SLA Actual/Previous],",
              "            ,",
              "            DESC,",
              "            DENSE",
              "        )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "bc477286-edfa-4974-acf7-fa241d80862b"
          },
          {
            "name": "Top N Skill %SLA Growth",
            "description": "Ranking",
            "displayFolder": "Top/Bottom SLA Comp. - SLA Comp.",
            "expression": "IF([Rank Skill %SLA Growth]<= 'TopN'[TopN Value],[% SLA Actual/Previous])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ca88684b-601b-4d5b-9638-c171b6679656"
          },
          {
            "name": "Top N Resources %SLA Growth",
            "description": "Ranking",
            "displayFolder": "Top/Bottom SLA Comp. - SLA Comp.",
            "expression": "IF([Rank Resource %SLA Growth]<= 'TopN'[TopN Value],[% SLA Actual/Previous])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "61dad146-7353-4892-80ea-45140fbe25e7"
          },
          {
            "name": "Ranking Dinmico % SLA Grow/Decre.",
            "description": "Ranking",
            "displayFolder": "Ranking SLA Comp.",
            "expression": [
              "",
              "IF(",
              "    VALUES('Macro Tema'[Macro Tema])=\"Skill\", ",
              "    [Top N Skill %SLA Growth],",
              "    IF(VALUES('Macro Tema'[Macro Tema])=\"Category\",",
              "    [Top N Category %SLA Growth],",
              "    IF(VALUES('Macro Tema'[Macro Tema]) = \"Resource Name\",[Top N Resources %SLA Growth],",
              "    [Top N Affec. Site %SLA Growth])))"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "317f268f-6fd5-4a8a-857b-4f093795e625"
          },
          {
            "name": "Rank Resource %SLA Growth",
            "description": "Ranking",
            "displayFolder": "Ranking SLA Comp.",
            "expression": [
              "",
              "SWITCH(",
              "    [Order Type],",
              "    \"Ascending\", ",
              "        RANKX(",
              "            ALL(metric[Resource Name]),",
              "            [% SLA Actual/Previous],",
              "            ,",
              "            ASC,",
              "            DENSE",
              "        ),",
              "    \"Descending\",",
              "        RANKX(",
              "            ALL(metric[Resource Name]),",
              "            [% SLA Actual/Previous],",
              "            ,",
              "            DESC,",
              "            DENSE",
              "        )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "3c7fde4b-b42b-4a59-9d7f-353c51c75f9e"
          },
          {
            "name": "Rank Category %SLA Growth",
            "description": "Ranking",
            "displayFolder": "Ranking SLA Comp.",
            "expression": [
              "",
              "SWITCH(",
              "    [Order Type],",
              "    \"Ascending\", ",
              "        RANKX(",
              "            ALL(metric[Category]),",
              "            [% SLA Actual/Previous],",
              "            ,",
              "            ASC,",
              "            DENSE",
              "        ),",
              "    \"Descending\",",
              "        RANKX(",
              "            ALL(metric[Category]),",
              "            [% SLA Actual/Previous],",
              "            ,",
              "            DESC,",
              "            DENSE",
              "        )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "05cb7e86-b51d-427f-bb59-b7713553572f"
          },
          {
            "name": "Top N Category %SLA Growth",
            "description": "Ranking",
            "displayFolder": "Top/Bottom SLA Comp. - SLA Comp.",
            "expression": [
              "",
              "IF([Rank Category %SLA Growth]<= 'TopN'[TopN Value],",
              "[% SLA Actual/Previous])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "aa4c8474-e67d-426b-aec7-2c4a10a1a6af"
          },
          {
            "name": "Rank Affec. Site %SLA Growth",
            "description": "Ranking",
            "displayFolder": "Ranking SLA Comp.",
            "expression": [
              "",
              "SWITCH(",
              "    [Order Type],",
              "    \"Ascending\", ",
              "        RANKX(",
              "            ALL(metric[Affected Site]),",
              "            [% SLA Actual/Previous],",
              "            ,",
              "            ASC,",
              "            DENSE",
              "        ),",
              "    \"Descending\",",
              "        RANKX(",
              "            ALL(metric[Affected Site]),",
              "            [% SLA Actual/Previous],",
              "            ,",
              "            DESC,",
              "            DENSE",
              "        )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "02933125-076c-4d01-9b47-1e6f1351e99c"
          },
          {
            "name": "Top N Affec. Site %SLA Growth",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Top/Bottom SLA Comp. - SLA Comp.",
            "expression": [
              "",
              "IF([Rank Affec. Site %SLA Growth]<= 'TopN'[TopN Value],",
              "[% SLA Actual/Previous])"
            ],
            "lineageTag": "de7dcc00-e4c6-46a5-922a-74fca1027a20"
          },
          {
            "name": "Last Month Count SLA Breached",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "CALCULATE(",
              "    sum(F_main[sla_breached_internal]),",
              "    dCalendar[Check_Relative Period]=TRUE(),",
              "    DATEADD(dCalendar[Data],-1,MONTH))"
            ],
            "formatString": "0",
            "lineageTag": "0c268d5a-5835-4117-9612-fd62b7361748"
          },
          {
            "name": "SLA Breached Actual/Previous",
            "displayFolder": "SLA Breached",
            "expression": "[Count - SLA Breached] - [Last Month Count SLA Breached]",
            "formatString": "0",
            "lineageTag": "4ba1c9e0-abb5-44c1-b26f-c5d6f1ad84ed"
          },
          {
            "name": "Top N Affec. Site Count SLA Breached",
            "displayFolder": "Top/Bottom Count SLA Breached - SLA Comp.",
            "expression": [
              "",
              "IF(",
              "    [Rank Affec. Site %SLA Growth]<= 'TopN'[TopN Value],",
              "    [Count - SLA Breached]",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "9bd90aad-de28-4bbf-b83a-1704b8651ef1"
          },
          {
            "name": "Top N Skill Count SLA Breached",
            "displayFolder": "Top/Bottom Count SLA Breached - SLA Comp.",
            "expression": [
              "",
              "IF(",
              "    [Rank Skill %SLA Growth]<= 'TopN'[TopN Value],",
              "    [Count - SLA Breached]",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "8f74016e-322c-49a6-b745-a9ccb97557d0"
          },
          {
            "name": "Top N Category Count SLA Breached",
            "displayFolder": "Top/Bottom Count SLA Breached - SLA Comp.",
            "expression": [
              "",
              "IF(",
              "    [Rank Category %SLA Growth]<= 'TopN'[TopN Value],",
              "    [Count - SLA Breached]",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "c3bfac75-5023-4588-af31-64ef6c726a3e"
          },
          {
            "name": "Top N Resource Count SLA Breached",
            "displayFolder": "Top/Bottom Count SLA Breached - SLA Comp.",
            "expression": [
              "",
              "IF(",
              "    [Rank Resource %SLA Growth]<= 'TopN'[TopN Value],",
              "    [Count - SLA Breached]",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "5b7c5247-a214-4f37-8cc5-3b2102d1d567"
          },
          {
            "name": "Ranking Dinmico SLA Breached Grow/Decre.",
            "displayFolder": "Top/Bottom Count SLA Breached - SLA Comp.",
            "expression": [
              "",
              "IF(",
              "    VALUES('Macro Tema'[Macro Tema])=\"Skill\", ",
              "    [Top N Skill Count SLA Breached],",
              "    IF(VALUES('Macro Tema'[Macro Tema])=\"Category\",",
              "    [Top N Category Count SLA Breached],",
              "    IF(VALUES('Macro Tema'[Macro Tema]) = \"Resource Name\",[Top N Resource Count SLA Breached],",
              "    [Top N Affec. Site Count SLA Breached])))"
            ],
            "formatString": "0",
            "lineageTag": "de697ea3-1bbe-4de0-aba8-76a53318d0d2"
          },
          {
            "name": "Top N Skill % SLA Achiev.",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Top/Bottom % SLA Achiev. - SLA Comp.",
            "expression": [
              "",
              "IF(",
              "    [Rank Skill %SLA Growth]<= 'TopN'[TopN Value],",
              "    [% SLA Achievement]",
              "    )"
            ],
            "lineageTag": "a77c20d4-7635-4362-91db-4680ef37a744"
          },
          {
            "name": "Top N Resource %SLA Achiev.",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Top/Bottom % SLA Achiev. - SLA Comp.",
            "expression": [
              "",
              "IF(",
              "    [Rank Resource %SLA Growth]<= 'TopN'[TopN Value],",
              "    [% SLA Achievement]",
              "    )"
            ],
            "lineageTag": "78d25754-3cf2-435a-a158-8a79c97eb4e1"
          },
          {
            "name": "Top N Category % SLA Achiev.",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Top/Bottom % SLA Achiev. - SLA Comp.",
            "expression": [
              "",
              "IF(",
              "    [Rank Category %SLA Growth]<= 'TopN'[TopN Value],",
              "    [% SLA Achievement]",
              "    )"
            ],
            "lineageTag": "6f7ac7fe-4b91-4e77-8002-89d330326776"
          },
          {
            "name": "Top N Affec. Site % SLA Achiev.",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Top/Bottom % SLA Achiev. - SLA Comp.",
            "expression": [
              "",
              "IF(",
              "    [Rank Affec. Site %SLA Growth]<= 'TopN'[TopN Value],",
              "    [% SLA Achievement]",
              "    )"
            ],
            "lineageTag": "f676fec8-7a88-449c-853c-93f11303c467"
          },
          {
            "name": "Ranking Dinmico % SLA Achievem.",
            "displayFolder": "Top/Bottom % SLA Achiev. - SLA Comp.",
            "expression": [
              "",
              "IF(",
              "    VALUES('Macro Tema'[Macro Tema])=\"Skill\", ",
              "    [Top N Skill % SLA Achiev.],",
              "    IF(VALUES('Macro Tema'[Macro Tema])=\"Category\",",
              "    [Top N Category % SLA Achiev.],",
              "    IF(VALUES('Macro Tema'[Macro Tema]) = \"Resource Name\",[Top N Resource %SLA Achiev.],",
              "    [Top N Affec. Site % SLA Achiev.])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7c3bcdd0-0be9-47fe-9a26-46ec19a22036"
          },
          {
            "name": "Rank Affec. Site %SLA Achiev.",
            "displayFolder": "Ranking SLA Achiev",
            "expression": [
              "",
              "SWITCH(",
              "    [Order Type],",
              "    \"Ascending\", ",
              "        RANKX(",
              "            ALL(metric[Affected Site]),",
              "            [% SLA Achievement],",
              "            ,",
              "            ASC,",
              "            DENSE",
              "        ),",
              "    \"Descending\",",
              "        RANKX(",
              "            ALL(metric[Affected Site]),",
              "            [% SLA Achievement],",
              "            ,",
              "            DESC,",
              "            DENSE",
              "        )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "024d3325-5285-4378-98ea-fc5a458e1fdc"
          },
          {
            "name": "Rank Category %SLA Achiev.",
            "displayFolder": "Ranking SLA Achiev",
            "expression": [
              "",
              "SWITCH(",
              "    [Order Type],",
              "    \"Ascending\", ",
              "        RANKX(",
              "            ALL(metric[Category]),",
              "            [% SLA Achievement],",
              "            ,",
              "            ASC,",
              "            DENSE",
              "        ),",
              "    \"Descending\",",
              "        RANKX(",
              "            ALL(metric[Category]),",
              "            [% SLA Achievement],",
              "            ,",
              "            DESC,",
              "            DENSE",
              "        )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f4b588ba-29b0-44d5-abd5-2583bd57b088"
          },
          {
            "name": "Rank Resource %SLA Achiev.",
            "displayFolder": "Ranking SLA Achiev",
            "expression": [
              "",
              "SWITCH(",
              "    [Order Type],",
              "    \"Ascending\", ",
              "        RANKX(",
              "            ALL(metric[Resource Name]),",
              "            [% SLA Achievement],",
              "            ,",
              "            ASC,",
              "            DENSE",
              "        ),",
              "    \"Descending\",",
              "        RANKX(",
              "            ALL(metric[Resource Name]),",
              "            [% SLA Achievement],",
              "            ,",
              "            DESC,",
              "            DENSE",
              "        )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c458923e-b9f0-4f2b-834d-9a3897492cb8"
          },
          {
            "name": "Rank Skill %SLA Achiev.",
            "displayFolder": "Ranking SLA Achiev",
            "expression": [
              "",
              "SWITCH(",
              "    [Order Type],",
              "    \"Ascending\", ",
              "        RANKX(",
              "            ALL(metric[Skill]),",
              "            [% SLA Achievement],",
              "            ,",
              "            ASC,",
              "            DENSE",
              "        ),",
              "    \"Descending\",",
              "        RANKX(",
              "            ALL(metric[Skill]),",
              "            [% SLA Achievement],",
              "            ,",
              "            DESC,",
              "            DENSE",
              "        )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5add1bc2-5efe-4844-a238-edc70bb5c53f"
          },
          {
            "name": "Top N Affec. Site % SLA Achiev. - SLA Achiev.",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2 - Top/Bottom % SLA Achiev. - SLA Achiev.",
            "expression": [
              "",
              "//Retorna os X top valores baseado no Rank do SLA Achiev. e retorna o SLA Achiev.",
              "IF(",
              "    [Rank Affec. Site %SLA Achiev.]<= 'TopN'[TopN Value],",
              "    [% SLA Achievement]",
              "    )"
            ],
            "lineageTag": "5da24404-af7a-4dbe-85a5-6516146d2238"
          },
          {
            "name": "Top N Category % SLA Achiev. - SLA Achiev.",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2 - Top/Bottom % SLA Achiev. - SLA Achiev.",
            "expression": [
              "",
              " //Retorna os X top valores baseado no Rank do SLA Achiev. e retorna o SLA Achiev.",
              "IF(",
              "    [Rank Category %SLA Achiev.]<= 'TopN'[TopN Value],",
              "    [% SLA Achievement]",
              "    )"
            ],
            "lineageTag": "4b8a18ae-f85f-484d-86ba-c6f35cb7bad7"
          },
          {
            "name": "Top N Resource %SLA Achiev. - SLA Achiev.",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2 - Top/Bottom % SLA Achiev. - SLA Achiev.",
            "expression": [
              "",
              "//Retorna os X top valores baseado no Rank do SLA Achiev. e retorna o SLA Achiev.",
              "IF(",
              "    [Rank Resource %SLA Achiev.]<= 'TopN'[TopN Value],",
              "    [% SLA Achievement]",
              "    )"
            ],
            "lineageTag": "3b56e846-cf48-460a-aa34-75ff9a19a2d9"
          },
          {
            "name": "Top N Skill % SLA Achiev. - SLA Achiev.",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2 - Top/Bottom % SLA Achiev. - SLA Achiev.",
            "expression": [
              "",
              "//Retorna os X top valores baseado no Rank do SLA Achiev. e retorna o SLA Achiev.",
              "IF(",
              "    [Rank Skill %SLA Achiev.]<= 'TopN'[TopN Value],",
              "    [% SLA Achievement]",
              "    )"
            ],
            "lineageTag": "c5789a4e-2d43-4a1b-8c41-81ca3e0669d1"
          },
          {
            "name": "Ranking Dinmico % SLA Achievem. - SLA Achiev.",
            "displayFolder": "2 - Top/Bottom % SLA Achiev. - SLA Achiev.",
            "expression": [
              "",
              "IF(",
              "    VALUES('Macro Tema'[Macro Tema])=\"Skill\", ",
              "    [Top N Skill % SLA Achiev. - SLA Achiev.],",
              "    IF(VALUES('Macro Tema'[Macro Tema])=\"Category\",",
              "    [Top N Category % SLA Achiev. - SLA Achiev.],",
              "    IF(VALUES('Macro Tema'[Macro Tema]) = \"Resource Name\",[Top N Resource %SLA Achiev. - SLA Achiev.],",
              "    [Top N Affec. Site % SLA Achiev. - SLA Achiev.])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d21d0b9c-d02e-47ae-bad2-a23a965418e5"
          },
          {
            "name": "Volume Actual/Previous",
            "displayFolder": "Volume of Tickets",
            "expression": "[Total Tickets] -  [Last Month - Total Tickets]",
            "formatString": "0",
            "lineageTag": "5310e879-2cb6-4430-a71e-6ddc8e295595"
          },
          {
            "name": "Count SLA - Breached/Total",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "DIVIDE(",
              "    [Count - SLA Breached],",
              "    CALCULATE([Count - SLA Breached],",
              "     ALL(metric[Skill],metric[Resource Name])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8b826c51-4e47-4474-97fb-dde69a67e19f"
          },
          {
            "name": "Relative Volume",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(metric[n_sla]),",
              "    CALCULATE(SUM(metric[n_sla]),",
              "     ALL(metric[Skill],metric[Resource Name],metric[Company])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4d5dd50e-be68-46af-897c-e1f2db6217a3"
          },
          {
            "name": "Teste Peso SLA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Count SLA - Breached/Total]*100/9.36",
            "lineageTag": "fb071d75-84cf-4d85-8e55-b5f481227193"
          },
          {
            "name": "Teste Peso Volume",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Relative Volume]*100/7.18",
            "lineageTag": "351bd7a1-3037-487c-89ae-55ccb690ce6e"
          },
          {
            "name": "Teste peso final",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Teste Peso SLA] - [Teste Peso Volume]",
            "lineageTag": "8cdbf6cc-4f7f-4a1c-98c7-34e37abfe24e"
          },
          {
            "name": "%Volume Actual/Previous",
            "expression": [
              "",
              "IF([Total Tickets] >0,",
              "DIVIDE(",
              "[Total Tickets],",
              "[Last Month - Total Tickets]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3aeb0e38-568b-4d41-a0a1-41fcc8a01e67"
          },
          {
            "name": "Last Month n SLA",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "CALCULATE(",
              "    sum(F_main[sla_internal_count]),",
              "    dCalendar[Check_Relative Period]=TRUE(),",
              "    DATEADD(dCalendar[Data],-1,MONTH))"
            ],
            "formatString": "0",
            "lineageTag": "4fa99d6d-e35c-4121-8b17-e41e6e703a74"
          },
          {
            "name": "n SLA",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "SUM(metric[n_sla])"
            ],
            "formatString": "0",
            "lineageTag": "279d6846-52f5-4422-9a5a-1f06c1bb15d3"
          },
          {
            "name": "Count Problem",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Tickets],",
              "    'metric'[Problem] <> \"NA\")"
            ],
            "formatString": "0",
            "lineageTag": "e2bc158d-ecb1-41e7-b5eb-85ac6f49e1f2"
          },
          {
            "name": "Count NO Problem",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(metric),",
              "    'metric'[Problem] = \"NA\")"
            ],
            "formatString": "0",
            "lineageTag": "84b9b277-8dd9-40c5-9d64-c07a76c0273d"
          },
          {
            "name": "% Problem",
            "expression": [
              "",
              "DIVIDE(",
              "    [Count Problem],",
              "    [Total Tickets])"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "a3239a32-df12-4a13-9b99-4b484bfbdbe3"
          },
          {
            "name": "Last month - Exclusive volume",
            "expression": [
              "",
              "IF(",
              "    [Last Month - Total Tickets]>0 &&[Total Tickets]=0,",
              "    [Last Month - Total Tickets])"
            ],
            "formatString": "0",
            "lineageTag": "09abf0ae-942e-446d-9124-945434aa6bc8"
          },
          {
            "name": "% Total tickets / All",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Tickets],",
              "    CALCULATE(",
              "        [Total Tickets],",
              "        ALL(dCalendar[Data])",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f268368f-de16-42a6-919f-ee4dbd3c6b6a"
          },
          {
            "name": "Tickets - YTD",
            "expression": [
              "",
              "CALCULATE(",
              "        [Total Tickets],",
              "        ALL(dCalendar[Data], dCalendar[Month Name])",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "2d0166e0-59c6-4a1f-8c7b-bd2422bd307c"
          },
          {
            "name": "% Problem - Relative volume",
            "expression": [
              "",
              "DIVIDE(",
              "    [Count Problem],",
              "    [Total Tickets]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "a3d6b144-7285-4daa-9df6-215ef9f97b6e"
          },
          {
            "name": "% SLA Achiev. - YTD",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "CALCULATE(",
              "    [% SLA Achievement],",
              "    ALL(dCalendar[Data],dCalendar[Month Name])",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0a297dac-21d0-4bdd-9511-b488843e3430"
          },
          {
            "name": "Count - SLA Breached YTD",
            "expression": [
              "",
              "CALCULATE(",
              "    [Count - SLA Breached],",
              "    ALL(dCalendar[Data])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "dd11389a-e612-497d-9bbe-f2b35e848624"
          },
          {
            "name": "n SLA YTD",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "CALCULATE(",
              "    [n SLA],",
              "    ALL(dCalendar[Data])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b58c5355-3dee-4303-a661-843a18f56548"
          },
          {
            "name": "Relative Volume (SLA) YTD",
            "expression": [
              "",
              "CALCULATE(",
              "    [Relative Volume],",
              "    ALL(dCalendar[Data])",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "383d45de-a513-48ee-a27b-fd71a5ace975"
          },
          {
            "name": "Last Month - Relative Volume",
            "expression": [
              "",
              "DIVIDE(",
              "    [Last Month n SLA],",
              "    CALCULATE([Last Month n SLA],",
              "     ALL(metric[Skill],metric[Resource Name],metric[Company])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "82c2707b-ffe3-44e9-a9e0-9e9393c7a869"
          },
          {
            "name": "% SLA Breached / ALL",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "DIVIDE(",
              "    [Count - SLA Breached],",
              "    CALCULATE(",
              "        [Count - SLA Breached],",
              "        ALL(metric[Skill],metric[Resource Name],metric[Company])",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bf1c5160-56fe-4a48-ad06-a7f17a96a10c"
          },
          {
            "name": "Last Month - % SLA Breached / ALL",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "DIVIDE(",
              "    [Last Month Count SLA Breached],",
              "    CALCULATE(",
              "        [Last Month Count SLA Breached],",
              "        ALL(metric[Skill],metric[Resource Name],metric[Company])",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8fe9ee5e-d5cc-46a4-ad38-06a2a83511ef"
          },
          {
            "name": "% SLA Breached Actual/Previous",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "IF(",
              "    [Total Tickets]>0 && [Last Month - Total Tickets]>0,",
              "    [% SLA Breached / ALL] ",
              "    - ",
              "    [Last Month - % SLA Breached / ALL])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "941bb886-03b9-42ee-8be9-37705782f9c5"
          },
          {
            "name": "% SLA Breached / ALL - YTD",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "DIVIDE([Count - SLA Breached YTD],",
              "    CALCULATE(",
              "        [Count - SLA Breached YTD],",
              "        ALL(metric[Skill],metric[Resource Name],metric[Company])",
              "    ))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2cf923ed-99f7-4808-992f-73b48521a365"
          },
          {
            "name": "% Relative Volume -  Actual/Previous",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "IF(",
              "    [Total Tickets]>0 && [Last Month - Total Tickets]>0,",
              "    [Relative Volume] - ",
              "    [Last Month - Relative Volume])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "66c35490-f031-48aa-b2f0-371d51f0db52"
          },
          {
            "name": "% SLA Breached / ALL - Skill",
            "expression": [
              "IF([Count - SLA Breached]>0,",
              "DIVIDE(",
              "    [Count - SLA Breached],",
              "    CALCULATE(",
              "        [Count - SLA Breached],",
              "        ALL(metric[Resource Name],metric[Priority],metric[Company],metric[Sub Cause])",
              "    )",
              "))"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "8431c730-3aad-438a-a2d8-124c4b24c24c"
          },
          {
            "name": "Last Month - % SLA Breached / ALL - Skill",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "DIVIDE(",
              "    [Last Month Count SLA Breached],",
              "    CALCULATE(",
              "        [Last Month Count SLA Breached],",
              "        ALL(metric[Company],metric[Resource Name],metric[Priority],metric[Sub Cause])",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "52a2a9d8-d346-43f1-ba03-3d8ef5eb1413"
          },
          {
            "name": "% SLA Breached Actual/Previous - Skill",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "IF(",
              "    [Total Tickets]>0 && [Last Month - Total Tickets]>0,",
              "    [% SLA Breached / ALL - Skill] ",
              "    - ",
              "    [Last Month - % SLA Breached / ALL - Skill])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ec90ba9d-8741-422b-a69d-281d6bacb41a"
          },
          {
            "name": "% SLA Breached / ALL - YTD Skill",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "DIVIDE([Count - SLA Breached YTD],",
              "    CALCULATE(",
              "        [Count - SLA Breached YTD],",
              "        ALL(metric[Company],metric[Resource Name],metric[Priority],metric[Sub Cause])",
              "    ))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "53e964af-f0af-4832-85b4-7daa0d9abb32"
          },
          {
            "name": "Relative Volume - Skill",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(metric[n_sla]),",
              "    CALCULATE(SUM(metric[n_sla]),",
              "     ALL(metric[Sub Cause],metric[Resource Name],metric[Priority],metric[Company])))"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "93e58858-ff99-4d10-a898-b50d13fc3f6b"
          },
          {
            "name": "Last Month - Relative Volume - Skill",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "DIVIDE(",
              "    [Last Month n SLA],",
              "    CALCULATE([Last Month n SLA],",
              "     ALL(metric[Company],metric[Resource Name],metric[Priority],metric[Sub Cause])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1aa16eb5-5aab-4780-9bdd-6c8583510b8e"
          },
          {
            "name": "% Relative Volume -  Actual/Previous - Priority",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "IF(",
              "    [Total Tickets]>0 && [Last Month - Total Tickets]>0,",
              "    [Relative Volume - Skill] - ",
              "    [Last Month - Relative Volume - Skill])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3d1e694c-16ad-4654-9b14-5e250478a7af"
          },
          {
            "name": "Relative Volume (SLA) YTD - Skill",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "CALCULATE(",
              "    [Relative Volume - Skill],",
              "    ALL(dCalendar[Data])",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7d9777b6-2186-426b-92af-6f591b0fe88d"
          },
          {
            "name": "first day problem",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    FIRSTDATE(",
              "        metric[Closed - Date]),",
              "        ALL(dCalendar[Data])",
              ")"
            ],
            "formatString": "mmmm d",
            "lineageTag": "ab99051e-bb93-420f-91a2-3c34a669354e"
          },
          {
            "name": "Tickets Breached",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(F_main[ticket_number]),",
              "    'F_main'[sla_breached_internal] >0,",
              "    USERELATIONSHIP(dCalendar[Data],F_main[resolved_at_formated]))"
            ],
            "formatString": "0",
            "lineageTag": "7c6381fd-3cb7-4ba6-adff-ab40f2ed2297"
          },
          {
            "name": "% Development",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT(metric[Number]),",
              "    metric[Sub Cause]=\"Development\"),",
              "COUNT(metric[Number])",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "660ac522-5eab-442f-9b21-3cb975ae1061"
          },
          {
            "name": "Count Development",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "CALCULATE(",
              "    [Resolved Tickets],",
              "    'F_main'[sub_cause_name_inc]=\"Development\")"
            ],
            "formatString": "0",
            "lineageTag": "7fdc73bf-2b3f-4140-a6c1-2697c5f59d7c"
          },
          {
            "name": "% SLA Achievement - Problem",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "IF(SUM(metric[n_sla]) >0,",
              "CALCULATE(",
              "1 - DIVIDE(",
              "    sum(metric[breached_sla]),",
              "    sum(metric[n_sla]),0),",
              "    FILTER(metric,metric[Problem] <>\"NA\"",
              "    )))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e337e927-882a-4e49-919e-cb524ab53cf7"
          },
          {
            "name": "% SLA Achievement - Without Problem",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "IF(SUM(metric[n_sla]) >0,",
              "CALCULATE(",
              "1 - DIVIDE(",
              "    sum(metric[breached_sla]),",
              "    sum(metric[n_sla]),0),",
              "    FILTER(metric,metric[Problem] =\"NA\"",
              "    )))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "97fde962-ca12-4807-921f-08dc21fe44ff"
          },
          {
            "name": "% rate_problems",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT(Problems[number]),",
              "        Problems[DEVOPS_Closed]>DATE(2023,12,1)),",
              "    COUNT(Problems[number])",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "e5bf9587-96cc-4ba3-92b4-58a85464e1b0"
          },
          {
            "name": "TTR - Hours",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(metric[ttr]),",
              "    3600)"
            ],
            "lineageTag": "939f1261-1170-47da-a9a9-bcb8f495ec84"
          },
          {
            "name": "MTTR Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    [TTR - Hours],",
              "    DISTINCTCOUNT(metric[Number]))"
            ],
            "lineageTag": "d4f33f09-4580-4664-b08a-aa50bae28e33"
          },
          {
            "name": "TTR Days",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    [TTR - Hours],",
              "    24)"
            ],
            "lineageTag": "82edacaf-ea79-4a0b-a273-df1c7f732ac9"
          },
          {
            "name": "Ticket breched 6H TTR (P2)",
            "expression": [
              "",
              "CALCULATE(",
              "    count(metric[Number]),",
              "    'metric'[ttr] > 21000)"
            ],
            "formatString": "0",
            "lineageTag": "ed444196-6ce8-4bbe-8f6e-17c5a223ee63"
          },
          {
            "name": "% Ticket breched 6H TTR (P2)",
            "expression": [
              "",
              "DIVIDE(",
              "[Ticket breched 6H TTR (P2)],",
              "[Total Tickets])"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "9c17e446-9973-4c9a-8ade-dc3b041d2b0d"
          },
          {
            "name": "% TTR/ALL",
            "expression": [
              "",
              "[TTR - Hours]/17223.01"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0f60922b-c627-488d-a816-2eabe0e3b6f4"
          },
          {
            "name": "MTTR - Hour",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "AVERAGE(F_main[mttr_in_seconds])/3600"
            ],
            "lineageTag": "5ad8e19e-9f13-4eff-b2da-cbac1b70574f"
          },
          {
            "name": "% volume Rollout April/All",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\"})",
              "    ,",
              "CALCULATE(",
              "    COUNT(metric[Number]),",
              "    ALL(metric[Affected Site])",
              ")",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "3b4dade1-318b-4a27-83d6-9e44b1025b24"
          },
          {
            "name": "Rollout April - Analysis W.A.",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\"},",
              "    'metric'[Sub Cause] = \"Analysis without Action\" || 'metric'[Sub Cause] = \"Solved by user\" || 'metric'[Sub Cause] = \"No user response\")",
              "    ,",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\"})",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3e5f86a3-2add-4635-950d-6efd9d37516b"
          },
          {
            "name": "Rollout April - Develop.",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\"},",
              "    'metric'[Sub Cause] = \"Development\")",
              "    ,",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\"})",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "670a124f-5891-4618-8c54-aa2df36f0494"
          },
          {
            "name": "Rollout April - How To",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "        'metric'[Affected Site] IN {\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\"},",
              "        'metric'[Sub Cause] = \"How To\" || ",
              "        'metric'[Sub Cause] = \"How To - Palliative\" || ",
              "        'metric'[Sub Cause] = \"How To - User erro\" || ",
              "        SEARCH(\"redirec\", 'metric'[Sub Cause], 1, 0) > 0",
              "    ),",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "        'metric'[Affected Site] IN {\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\"}",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d341e27c-5146-444d-89ba-06b4da88e3f2"
          },
          {
            "name": "% volume Rollout May/All",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\"})",
              "    ,",
              "CALCULATE(",
              "    COUNT(metric[Number]),",
              "    ALL(metric[Affected Site])",
              ")",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "87cab5a8-0ed0-49c9-8f1f-e4d64a11a9bd"
          },
          {
            "name": "Rollout May - Analysis W.A.",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\"},",
              "    'metric'[Sub Cause] = \"Analysis without Action\" || 'metric'[Sub Cause] = \"Solved by user\" || 'metric'[Sub Cause] = \"No user response\")",
              "    ,",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\"})",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a3d93d0e-fa78-440f-8dec-0f910bce7ddd"
          },
          {
            "name": "Rollout May - How To",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\"},",
              "        'metric'[Sub Cause] = \"How To\" || ",
              "        'metric'[Sub Cause] = \"How To - Palliative\" || ",
              "        'metric'[Sub Cause] = \"How To - User erro\" || ",
              "        SEARCH(\"redirec\", 'metric'[Sub Cause], 1, 0) > 0",
              "    ),",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\"}",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f2a49eab-9984-4140-80a1-f427d4f90a47"
          },
          {
            "name": "Rollout May - Develop.",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\"},",
              "    'metric'[Sub Cause] = \"Development\")",
              "    ,",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\"})",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "61924003-6ca1-4472-8433-5bbd6a394e0d"
          },
          {
            "name": "% volume Rollout 2023/All",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"Cervejaria Belm\", \"CDR Belm\", \"CDR Sete Lagoas\", \"Cervejaria Colorado\", \"Cervejaria Wals\", \"Cervejaria guas Claras\", \"Cervejaria Juatuba\", \"Cervejaria Bohemia\", \"Cervejaria Lajes\", \"Fabrica BSA Grafica Vert\"})",
              "    ,",
              "CALCULATE(",
              "    COUNT(metric[Number]),",
              "    ALL(metric[Affected Site])",
              ")",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "82c8de5a-3246-452a-902c-a1e001428f48"
          },
          {
            "name": "Rollout 2023 - How To",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"Cervejaria Belm\", \"CDR Belm\", \"CDR Sete Lagoas\", \"Cervejaria Colorado\", \"Cervejaria Wals\", \"Cervejaria guas Claras\", \"Cervejaria Juatuba\", \"Cervejaria Bohemia\", \"Cervejaria Lajes\", \"Fabrica BSA Grafica Vert\"},",
              "        'metric'[Sub Cause] = \"How To\" || ",
              "        'metric'[Sub Cause] = \"How To - Palliative\" || ",
              "        'metric'[Sub Cause] = \"How To - User erro\" || ",
              "        SEARCH(\"redirec\", 'metric'[Sub Cause], 1, 0) > 0",
              "    ),",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"Cervejaria Belm\", \"CDR Belm\", \"CDR Sete Lagoas\", \"Cervejaria Colorado\", \"Cervejaria Wals\", \"Cervejaria guas Claras\", \"Cervejaria Juatuba\", \"Cervejaria Bohemia\", \"Cervejaria Lajes\", \"Fabrica BSA Grafica Vert\"}",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dd41b068-711f-4943-88a7-cab3235710b5"
          },
          {
            "name": "Rollout 2023 - Analysis W.A.",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"Cervejaria Belm\", \"CDR Belm\", \"CDR Sete Lagoas\", \"Cervejaria Colorado\", \"Cervejaria Wals\", \"Cervejaria guas Claras\", \"Cervejaria Juatuba\", \"Cervejaria Bohemia\", \"Cervejaria Lajes\", \"Fabrica BSA Grafica Vert\"},",
              "    'metric'[Sub Cause] = \"Analysis without Action\" || 'metric'[Sub Cause] = \"Solved by user\" || 'metric'[Sub Cause] = \"No user response\")",
              "    ,",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"Cervejaria Belm\", \"CDR Belm\", \"CDR Sete Lagoas\", \"Cervejaria Colorado\", \"Cervejaria Wals\", \"Cervejaria guas Claras\", \"Cervejaria Juatuba\", \"Cervejaria Bohemia\", \"Cervejaria Lajes\", \"Fabrica BSA Grafica Vert\"})",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "efedfb98-ad34-4d27-8300-c9196ac55d15"
          },
          {
            "name": "Rollout 2023 - Develop.",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"Cervejaria Belm\", \"CDR Belm\", \"CDR Sete Lagoas\", \"Cervejaria Colorado\", \"Cervejaria Wals\", \"Cervejaria guas Claras\", \"Cervejaria Juatuba\", \"Cervejaria Bohemia\", \"Cervejaria Lajes\", \"Fabrica BSA Grafica Vert\"},",
              "    'metric'[Sub Cause] = \"Development\")",
              "    ,",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"Cervejaria Belm\", \"CDR Belm\", \"CDR Sete Lagoas\", \"Cervejaria Colorado\", \"Cervejaria Wals\", \"Cervejaria guas Claras\", \"Cervejaria Juatuba\", \"Cervejaria Bohemia\", \"Cervejaria Lajes\", \"Fabrica BSA Grafica Vert\"})",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f0577b66-4dbf-4a1d-92b7-17666840feb4"
          },
          {
            "name": "Rollout April - Volume",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\"})"
            ],
            "formatString": "0",
            "lineageTag": "7be89d04-fbf3-4b31-88a8-cf46df3a626d"
          },
          {
            "name": "% volume Rollout April/2023 Rollouts",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "        'metric'[Affected Site] IN {\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\"}",
              "    ),",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "        FILTER(",
              "            VALUES('metric'[Affected Site]),",
              "            'metric'[Affected Site] IN ",
              "            EXCEPT(",
              "                VALUES('metric'[Affected Site]), ",
              "                {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\", \"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\", \"F. Nova Minas\"}",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "04c60bca-d2bc-4d2f-93c5-f6f5c78df1fa"
          },
          {
            "name": "TESTE - % volume Rollout",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\", \"Cervejaria Belm\", \"CDR Belm\", \"CDR Sete Lagoas\", \"Cervejaria Colorado\", \"Cervejaria Wals\", \"Cervejaria guas Claras\", \"Cervejaria Juatuba\", \"Cervejaria Bohemia\", \"Cervejaria Lajes\", \"Fabrica BSA Grafica Vert\", \"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\"})",
              "    ,",
              "CALCULATE(",
              "    COUNT(metric[Number]),",
              "    ALL(metric[Affected Site])",
              ")",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "78de9cad-4e57-4c77-ac97-de8fd4157d04"
          },
          {
            "name": "% volume Rollout July/All",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\"})",
              "    ,",
              "CALCULATE(",
              "    COUNT(metric[Number]),",
              "    ALL(metric[Affected Site])",
              ")",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "27e439d3-cefe-4414-95ea-5db1b28557e1"
          },
          {
            "name": "Rollout July - Analysis W.A.",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\"},",
              "    'metric'[Sub Cause] = \"Analysis without Action\" || 'metric'[Sub Cause] = \"Solved by user\" || 'metric'[Sub Cause] = \"No user response\")",
              "    ,",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\"})",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "01340349-5d13-42b2-9811-08d95037c703"
          },
          {
            "name": "Rollout July - How To",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\"},",
              "        'metric'[Sub Cause] = \"How To\" || ",
              "        'metric'[Sub Cause] = \"How To - Palliative\" || ",
              "        'metric'[Sub Cause] = \"How To - User erro\" || ",
              "        SEARCH(\"redirec\", 'metric'[Sub Cause], 1, 0) > 0",
              "    ),",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\"}",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1c62ebd0-20c2-4cc3-a185-b84a61b9056e"
          },
          {
            "name": "Rollout July - Develop.",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\"},",
              "    'metric'[Sub Cause] = \"Development\")",
              "    ,",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\"})",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7ce9ee66-a72f-48cd-a568-47d53ca6bbfd"
          },
          {
            "name": "Rollout May - MAster Data.",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\"},",
              "    'metric'[Sub Cause] = \"Master Data\")",
              "    ,",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "'metric'[Affected Site] IN {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\"})",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e11a7310-6016-4664-9ed2-0619e60a8498"
          },
          {
            "name": "% volume Rollout May/2023 Rollouts",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "        'metric'[Affected Site] IN {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\"}",
              "    ),",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "        FILTER(",
              "            VALUES('metric'[Affected Site]),",
              "            'metric'[Affected Site] IN ",
              "            EXCEPT(",
              "                VALUES('metric'[Affected Site]), ",
              "                {\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\", \"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\", \"F. Nova Minas\"}",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4b13c822-b5a1-4c5a-ab33-cbbd80b1ec9b"
          },
          {
            "name": "Rollout May - Volume",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\"})"
            ],
            "formatString": "0",
            "lineageTag": "f9506886-609b-4360-b91d-f287369ef0c0"
          },
          {
            "name": "% volume Rollout July/2023 Rollouts",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "        'metric'[Affected Site] IN {\"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\", \"F. Nova Minas\"}",
              "    ),",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "        FILTER(",
              "            VALUES('metric'[Affected Site]),",
              "            'metric'[Affected Site] IN ",
              "            EXCEPT(",
              "                VALUES('metric'[Affected Site]), ",
              "                {\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\", \"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\"}",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "29b3a50e-ab30-4621-b6a0-0eab22963be2"
          },
          {
            "name": "Rollout July - Volume",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Affected Site] IN {\"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\", \"F. Nova Minas\"})"
            ],
            "formatString": "0",
            "lineageTag": "b8b0684b-d6fb-4cf0-947f-8d84fda0c0b4"
          },
          {
            "name": "% volume Rollout 2023/withou 2024",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        [Total Tickets],",
              "        FILTER(",
              "            VALUES('metric'[Affected Site]),",
              "            'metric'[Affected Site] IN ",
              "            EXCEPT(",
              "                VALUES('metric'[Affected Site]), ",
              "                {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\", \"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\", \"F. Nova Minas\",\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\"}",
              "            )",
              "        )",
              "    ),",
              "    [Total Tickets]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e280a3df-6b66-4386-bdf7-0867dfd14205"
          },
          {
            "name": "SLA Achiev. 2023",
            "expression": [
              "",
              "CALCULATE([% SLA Achievement],",
              "FILTER(",
              "            VALUES('metric'[Affected Site]),",
              "            'metric'[Affected Site] IN ",
              "            EXCEPT(",
              "                VALUES('metric'[Affected Site]), ",
              "                {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\", \"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\", \"F. Nova Minas\",\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\"}",
              "            )",
              "        )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "44d76bf0-434b-4de7-9fb1-8742432b5f50"
          },
          {
            "name": "% How To",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "        'metric'[Sub Cause] = \"How To\" || ",
              "        'metric'[Sub Cause] = \"How To - Palliative\" || ",
              "        'metric'[Sub Cause] = \"How To - User error\" || ",
              "        SEARCH(\"redirec\", 'metric'[Sub Cause], 1, 0) > 0",
              "    ),",
              "    CALCULATE(",
              "        COUNT('metric'[Number]),",
              "        ALL(metric[Sub Cause])",
              ")",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "6ac436b3-4672-48c0-aa65-0cc66a6e2537"
          },
          {
            "name": "% Analysis W.A.",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Sub Cause] = \"Analysis without Action\" || 'metric'[Sub Cause] = \"Solved by user\" || 'metric'[Sub Cause] = \"No user response\")",
              "    ,",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    ALL(metric[Sub Cause])",
              ")",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f29dfdc9-d9d9-422e-b87b-7679dae8fa6a"
          },
          {
            "name": "% Develop.",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Sub Cause] = \"Development\")",
              "    ,",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    ALL(metric[Sub Cause])",
              ")",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "1b6ad3c0-7505-4318-a94d-799af3485d21"
          },
          {
            "name": "% Master Data",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Sub Cause] = \"Master Data\")",
              "    ,",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    ALL(metric[Sub Cause])",
              ")",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4aa2d836-eb78-44f8-a476-c942396d882f"
          },
          {
            "name": "% Func. Config.",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    'metric'[Sub Cause] = \"Functional Configuration\")",
              "    ,",
              "CALCULATE(",
              "    COUNT('metric'[Number]),",
              "    ALL(metric[Sub Cause])",
              ")",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "71c12679-86e0-4a24-9407-f6cce1d5adb7"
          },
          {
            "name": "Total Tickets Rollout 22 e 23",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Tickets],",
              "        FILTER(",
              "            VALUES('metric'[Affected Site]),",
              "            'metric'[Affected Site] IN ",
              "            EXCEPT(",
              "                VALUES('metric'[Affected Site]), ",
              "                {\"C. Macacu\", \"CDR BA\", \"CDR Bahia\", \"CRD Extrema\", \"F. Ag.Claras Sul\", \"F. Camacari\", \"F. Cuiaba\", \"F. Do Bem\", \"F. Latas Minas\", \"F. Teresina\", \"F. Vidros\", \"CDD Louveira\", \"F. Agudos\", \"F. Cebrasa\", \"F. Jacarei\", \"F. Maranhao\", \"F. Pernambuco\", \"F. Pirai\", \"F. Nova Minas\",\"Arousco Aromas\", \"Arousco Rolhas\", \"C. Ponta Grossa\", \"C. Uberlandia\", \"F. Aquiraz\", \"F. Barra Bonita\", \"F. Guarulhos\", \"F. Jundiai\", \"F. Levedura\", \"F. Manaus\", \"F. Maues\", \"F. Rio Janeiro\"}",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "462fb625-771d-4424-8f1c-f06738fe1da7"
          },
          {
            "name": "Distinc Analysts",
            "expression": [
              "",
              "DISTINCTCOUNT(metric[Resource Name])"
            ],
            "formatString": "0",
            "lineageTag": "4c9113bd-26b5-4462-b204-42b8e35277c5"
          },
          {
            "name": "Opened Tickets",
            "expression": [
              "",
              "COUNT(F_main[ticket_number])"
            ],
            "formatString": "0",
            "lineageTag": "37fad7f2-8b08-4af5-9e0b-d98870ed378b"
          },
          {
            "name": "Teste Total Resolved Tickets",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Tickets],",
              "    USERELATIONSHIP(dCalendar[Data],metric[Resolved - Date]))"
            ],
            "formatString": "0",
            "lineageTag": "df7c427d-b036-4b3b-b3b1-69c7981eda5d"
          },
          {
            "name": "% SLA Achievement Acumulado",
            "expression": [
              "",
              "CALCULATE(",
              "    [% SLA Achievement],  -- A medida original que voc j tem",
              "    FILTER(",
              "        ALL('dCalendar'[Data]),  -- Substitua 'Calendar' pela sua tabela de datas",
              "        'dCalendar'[Data] <= MAX('dCalendar'[Data])  -- Acumula at a data do contexto",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1a82d383-a54f-4333-8452-12970fe09f62"
          },
          {
            "name": "Waste",
            "expression": [
              "",
              "CALCULATE(",
              "    [Resolved Tickets],",
              "    'F_main'[sub_cause_name_inc]= \"Analysis Without Action\" || 'F_main'[sub_cause_name_inc] = \"Solved By User\" || 'F_main'[sub_cause_name_inc] = \"No user response\" || 'F_main'[sub_cause_name_inc] = \"How To\" || 'F_main'[sub_cause_name_inc] = \"How To - Palliative\" || 'F_main'[sub_cause_name_inc] = \"How To - User error\" || 'F_main'[sub_cause_name_inc] = \"Development\" || SEARCH(\"Redirec\", 'F_main'[sub_cause_name_inc], 1, 0) > 0",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "8ee4bcf1-c1b2-4dfe-b225-81047c2e2ae8"
          },
          {
            "name": "Count How To",
            "expression": [
              "",
              "CALCULATE(",
              "        [Resolved Tickets],",
              "        'F_main'[sub_cause_name_inc] = \"How To\" || ",
              "        'F_main'[sub_cause_name_inc] = \"How To - Palliative\" || ",
              "        'F_main'[sub_cause_name_inc] = \"How To - User error\" || ",
              "        SEARCH(\"Redirec\", 'F_main'[sub_cause_name_inc], 1, 0) > 0",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "4c9d58f6-e70a-4d3a-a29b-b3e9a4f191bd"
          },
          {
            "name": "Semana Referncia",
            "expression": [
              "",
              "DATEDIFF(DATE(2024,1,1),(LASTDATE(",
              "        STARTOFMONTH(dCalendar[Data])",
              "    ) - 1),DAY)",
              "    /7"
            ],
            "formatString": "0",
            "lineageTag": "f6541eb6-5811-4051-9298-067ff0dbeb88"
          },
          {
            "name": "Semana Atual",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "ROUNDDOWN(",
              "WEEKNUM(MAX(dCalendar[Data])) - [Semana Referncia],",
              "0)"
            ],
            "lineageTag": "7f0ebe93-2556-4394-8935-5e00953c32dd"
          },
          {
            "name": "SLA Achiev this week",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "VAR SemanaAtual = ROUNDUP([Semana Atual],0) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "RETURN",
              "CALCULATE(",
              "    [% SLA Achievement],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaAtual",
              "    )",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "1a75e1a2-0b26-4d64-a89b-f6a20a830eb8"
          },
          {
            "name": "SLA Achiev last week",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "VAR SemanaPassada = INT(ROUNDUP([Semana Atual],0) -1) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "VAR MesAtual = MONTH(TODAY())",
              "RETURN",
              "",
              "IF(SemanaPassada > 0,",
              "CALCULATE(",
              "    [% SLA Achievement],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaPassada && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              "),",
              "CALCULATE(",
              "    [% SLA Achievement],",
              "    FILTER(",
              "        ALL(dCalendar),  -- Volta 1 mes para trs se interferncia do calendrio",
              "        dCalendar[Week of Month] = 5 && dCalendar[Month] = (MesAtual - 1) && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              ")",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4fb1f6ea-e531-4e2b-b0b7-62fc8879a8de"
          },
          {
            "name": "% SLA Achiev This/Last (Week)",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "-- compara o SLA da semana tual com a interior de forma individual, no  o acumulado do ms",
              "[SLA Achiev this week]",
              "-",
              "[SLA Achiev last week]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "6861967d-1d85-4372-8b0e-b4973b7959d8"
          },
          {
            "name": "SLA Achiev last week Acumulado",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "VAR SemanaAtual = [Semana Atual] - 1 -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "RETURN",
              "CALCULATE(",
              "    [% SLA Achievement],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] <= SemanaAtual -- Calcula SLA do ms sem a semana atual",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1010a2bd-f1c0-427a-8e5f-4f1dbc8607bf"
          },
          {
            "name": "% SLA Achiev This/Last (Week) - Acumulado",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "-- compara o SLA da semana passada com o SLA do ms. Na prtica compara o impacto da semana atual no ms",
              "[% SLA Achievement]",
              "-",
              "[SLA Achiev last week Acumulado]",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b76ea045-3d10-4fa6-8bcb-016ba49697e4"
          },
          {
            "name": "Total Opened last week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR SemanaAtual = ROUNDUP([Semana Atual],0) - 2 -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "RETURN",
              "CALCULATE(",
              "    [Opened Tickets],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaAtual",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "badb4b43-5385-450d-a2cc-84b71bd94154"
          },
          {
            "name": "Total Opened this week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR SemanaAtual = ROUNDUP([Semana Atual],0) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "RETURN",
              "CALCULATE(",
              "    [Opened Tickets],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaAtual",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7a254fea-f9ef-40d2-9a4b-fa763ff50d9d"
          },
          {
            "name": "Opened Tickets this week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR SemanaAtual = ROUNDUP([Semana Atual],0) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "RETURN",
              "CALCULATE(",
              "    [Opened Tickets],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaAtual",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "015e860b-925a-4267-9853-3b1ffb52efeb"
          },
          {
            "name": "Opened Tickets last week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR SemanaPassada = INT(ROUNDUP([Semana Atual],0) -1) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "VAR MesAtual = MONTH(TODAY())",
              "RETURN",
              "",
              "IF(SemanaPassada > 0,",
              "CALCULATE(",
              "    [Opened Tickets],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaPassada && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6",
              "    )",
              "),",
              "CALCULATE(",
              "    [Opened Tickets],",
              "    FILTER(",
              "        ALL(dCalendar),  -- Volta 1 mes para trs se interferncia do calendrio",
              "        dCalendar[Week of Month] = 5 && dCalendar[Month] = (MesAtual - 1)",
              "        && dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6",
              "    )",
              ")",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7845813a-cbbb-4c79-92bd-154069d7f0cd"
          },
          {
            "name": "Opened tickets Actul/Prev (week)",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "-- diferena de fechamento da semana atual comparado com a semana anterior",
              "[Opened Tickets this week]",
              "-",
              "[Opened Tickets last week]"
            ],
            "formatString": "0",
            "lineageTag": "90fd14f3-1ac1-4ca1-a45e-a87047fc2502"
          },
          {
            "name": "Check Opened Tickets (week)",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "IF(",
              "    [Opened tickets Actul/Prev (week)] >0,",
              "    \"Increased\",",
              "    \"Decreased\")"
            ],
            "lineageTag": "4577352b-2c1e-4041-b468-68a063b44788"
          },
          {
            "name": "Waste this week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR SemanaAtual = ROUNDUP([Semana Atual],0) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "RETURN",
              "CALCULATE(",
              "    [Waste],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaAtual",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "383d4984-3de0-432f-85b8-b3dc70f2be5a"
          },
          {
            "name": "Waste last week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR SemanaPassada = INT(ROUNDUP([Semana Atual],0) -1) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "VAR MesAtual = MONTH(TODAY())",
              "RETURN",
              "",
              "IF(SemanaPassada > 0,",
              "CALCULATE(",
              "    [Waste],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaPassada && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              "),",
              "CALCULATE(",
              "    [Waste],",
              "    FILTER(",
              "        ALL(dCalendar),  -- Volta 1 mes para trs se interferncia do calendrio",
              "        dCalendar[Week of Month] = 5 && dCalendar[Month] = (MesAtual - 1) && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              ")",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ce09b510-efa1-40d9-a614-fc02bd733150"
          },
          {
            "name": "Waste Actual/Prev Week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "[Waste this week]",
              "-",
              "[Waste last week]"
            ],
            "formatString": "0",
            "lineageTag": "17eb2f68-34e2-4b56-8e73-02391ce89162"
          },
          {
            "name": "Check Waste (week)",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "IF(",
              "    [Waste Actual/Prev Week] >0,",
              "    \"Increased\",",
              "    \"Decreased\")"
            ],
            "lineageTag": "ae863485-d14f-4851-b7e5-a4571d454342"
          },
          {
            "name": "Developmetn this week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR SemanaAtual = ROUNDUP([Semana Atual],0) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "RETURN",
              "CALCULATE(",
              "    [Count Development],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaAtual",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ca292d5f-f8ca-46c5-b193-f38e2398a444"
          },
          {
            "name": "Development last week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR SemanaPassada = INT(ROUNDUP([Semana Atual],0) -1) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "VAR MesAtual = MONTH(TODAY())",
              "RETURN",
              "",
              "IF(SemanaPassada > 0,",
              "CALCULATE(",
              "    [Count Development],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaPassada && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              "),",
              "CALCULATE(",
              "    [Count Development],",
              "    FILTER(",
              "        ALL(dCalendar),  -- Volta 1 mes para trs se interferncia do calendrio",
              "        dCalendar[Week of Month] = 5 && dCalendar[Month] = (MesAtual - 1) && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              ")",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "cf56fb5d-2b49-47d4-b253-c426e43b19c3"
          },
          {
            "name": "Development Actual/Prev. (week)",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "[Developmetn this week]",
              "-",
              "[Development last week]"
            ],
            "formatString": "0",
            "lineageTag": "5ddf86df-f333-4d8e-8fc8-d2634b8474c7"
          },
          {
            "name": "Check Development (week)",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "IF(",
              "    [Development Actual/Prev. (week)] >0,",
              "    \"Increased\",",
              "    \"Decreased\")"
            ],
            "lineageTag": "a1c25ca4-d3a7-4e02-9266-3acc22383cae"
          },
          {
            "name": "How To this week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR SemanaAtual = ROUNDUP([Semana Atual],0) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "RETURN",
              "CALCULATE(",
              "    [Count How To],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaAtual",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6e29fe94-902f-429d-bbca-f05ff268ee91"
          },
          {
            "name": "How To last week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR SemanaPassada = INT(ROUNDUP([Semana Atual],0) -1) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "VAR MesAtual = MONTH(TODAY())",
              "RETURN",
              "",
              "IF(SemanaPassada > 0,",
              "CALCULATE(",
              "    [Count How To],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaPassada && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              "),",
              "CALCULATE(",
              "    [Count How To],",
              "    FILTER(",
              "        ALL(dCalendar),  -- Volta 1 mes para trs se interferncia do calendrio",
              "        dCalendar[Week of Month] = 5 && dCalendar[Month] = (MesAtual - 1) && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              ")",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "2d1ffe83-9645-454a-b94f-3f3315676aa7"
          },
          {
            "name": "How To Actul/Prev. (week)",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "[How To this week]",
              "-",
              "[How To last week]"
            ],
            "formatString": "0",
            "lineageTag": "5426b59a-1fed-44b7-84ca-964d258d1221"
          },
          {
            "name": "Check How To (week)",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "IF(",
              "    [How To Actul/Prev. (week)] >0,",
              "    \"Increased\",",
              "    \"Decreased\")"
            ],
            "lineageTag": "757c04f8-7857-4a12-aafd-ac3cca90ffca"
          },
          {
            "name": "% Waste this week",
            "expression": [
              "",
              "DIVIDE([Waste this week],[Opened Tickets this week])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "198a2826-c65e-4ee5-8f9a-183806c3f382"
          },
          {
            "name": "MTTR Horas formatadas",
            "expression": [
              "",
              "VAR Horas = INT([MTTR - Hour])  -- Parte inteira (horas)",
              "VAR Minutos = ROUND(( [MTTR - Hour] - Horas ) * 60, 0)  -- Parte decimal convertida em minutos",
              "RETURN ",
              "FORMAT(Horas, \"0\") & \":\" & FORMAT(Minutos, \"00\")",
              ""
            ],
            "lineageTag": "77d00750-e9bf-4f51-a692-36ce36ed3c34"
          },
          {
            "name": "Resolved Tickets this week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR SemanaAtual = ROUNDUP([Semana Atual],0) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "RETURN",
              "CALCULATE(",
              "    [Resolved Tickets],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaAtual",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "fe7ca2a4-54f6-415c-b6c1-21632ee71aba"
          },
          {
            "name": "Resolved tickets last week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR SemanaPassada = INT(ROUNDUP([Semana Atual],0) -1) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "VAR MesAtual = MONTH(TODAY())",
              "RETURN",
              "",
              "IF(SemanaPassada > 0,",
              "CALCULATE(",
              "    [Resolved Tickets],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaPassada && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              "),",
              "CALCULATE(",
              "    [Resolved Tickets],",
              "    FILTER(",
              "        ALL(dCalendar),  -- Volta 1 mes para trs se interferncia do calendrio",
              "        dCalendar[Week of Month] = 5 && dCalendar[Month] = (MesAtual - 1) && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              ")",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "9a6d7167-d29a-4906-9b04-00f7804d79fd"
          },
          {
            "name": "Resolved tickets Actul/Prev (week)",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "-- diferena de fechamento da semana atual comparado com a semana anterior",
              "[Resolved Tickets this week]",
              "-",
              "[Resolved tickets last week]"
            ],
            "formatString": "0",
            "lineageTag": "516376c9-c02d-4824-8ee7-25f38995c1f7"
          },
          {
            "name": "Breached Tickets this week",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR SemanaAtual = ROUNDUP([Semana Atual],0) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "RETURN",
              "CALCULATE(",
              "    [Tickets Breached],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaAtual",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "63c2dcc8-7765-45ac-bfee-025f4f106b47"
          },
          {
            "name": "Check Resolved tickets (week)",
            "expression": [
              "",
              "IF(",
              "    [Resolved tickets Actul/Prev (week)] >0,",
              "    \"Increased\",",
              "    \"Decreased\")"
            ],
            "lineageTag": "ccb9e636-8366-4839-8d73-8883a060cbc4"
          },
          {
            "name": "_mes anterior",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "MONTH(TODAY()) -1"
            ],
            "formatString": "0",
            "lineageTag": "bacaaad5-0c3d-4f4c-b6c7-81dc196e02bb"
          },
          {
            "name": "_TESTE1",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "VAR MesAtual = MONTH(TODAY()) - 1",
              "VAR TicketsMesAnterior = CALCULATE(",
              "    [Opened Tickets],",
              "    FILTER(",
              "        ALL(dCalendar),  -- Volta 1 mes para trs se interferncia do calendrio",
              "        dCalendar[Week of Month] = 5 && dCalendar[Month] = MesAtual",
              "    )",
              ")",
              "RETURN",
              "TicketsMesAnterior"
            ],
            "formatString": "0",
            "lineageTag": "d2db6af0-f9be-451d-ae7e-c8a5015905a5"
          },
          {
            "name": "MTTR this week",
            "expression": [
              "",
              "VAR SemanaAtual = ROUNDUP([Semana Atual],0) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "RETURN",
              "CALCULATE(",
              "    [MTTR Horas formatadas],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaAtual",
              "    )",
              ")"
            ],
            "lineageTag": "53b6cc50-c76f-48ec-bb28-a2dd29d974d3"
          },
          {
            "name": "MTTR last week",
            "expression": [
              "",
              "VAR SemanaPassada = INT(ROUNDUP([Semana Atual],0) -1) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "VAR MesAtual = MONTH(TODAY())",
              "RETURN",
              "",
              "IF(SemanaPassada > 0,",
              "CALCULATE(",
              "    [MTTR Horas formatadas],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaPassada && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              "),",
              "CALCULATE(",
              "    [MTTR Horas formatadas],",
              "    FILTER(",
              "        ALL(dCalendar),  -- Volta 1 mes para trs se interferncia do calendrio",
              "        dCalendar[Week of Month] = 5 && dCalendar[Month] = (MesAtual - 1) && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              ")",
              ")"
            ],
            "lineageTag": "4e464b6f-8a5e-4a4c-83be-9866dc0af815"
          },
          {
            "name": "MTTR This/Last (Week)",
            "expression": [
              "",
              "VAR mttr_diff = [MTTR this week - Decimal] - [MTTR last week - Decimal]",
              "VAR Horas = INT(mttr_diff)  -- Parte inteira (horas)",
              "VAR Minutos = ROUND((mttr_diff - Horas ) * 60, 0)  -- Parte decimal convertida em minutos",
              "RETURN ",
              "FORMAT(Horas, \"0\") & \":\" & FORMAT(Minutos, \"00\")"
            ],
            "lineageTag": "9e4a9087-6082-4654-933c-9400aec30ae7"
          },
          {
            "name": "MTTR this week - Decimal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR SemanaAtual = ROUNDUP([Semana Atual],0) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "RETURN",
              "CALCULATE(",
              "    [MTTR - Hour],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaAtual",
              "    )",
              ")"
            ],
            "lineageTag": "876baa81-b3a2-41de-85a3-e4c0ead6dbc5"
          },
          {
            "name": "MTTR last week - Decimal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR SemanaPassada = INT(ROUNDUP([Semana Atual],0) -1) -- arredonda p/ pegar o nmero da semana atual em valor inteiro",
              "VAR MesAtual = MONTH(TODAY())",
              "RETURN",
              "",
              "IF(SemanaPassada > 0,",
              "CALCULATE(",
              "    [MTTR - Hour],",
              "    FILTER(",
              "        dCalendar,",
              "        dCalendar[Week of Month] = SemanaPassada && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              "),",
              "CALCULATE(",
              "    [MTTR - Hour],",
              "    FILTER(",
              "        ALL(dCalendar),  -- Volta 1 mes para trs se interferncia do calendrio",
              "        dCalendar[Week of Month] = 5 && dCalendar[Month] = (MesAtual - 1) && ",
              "        dCalendar[Day of Week] <> 5 && dCalendar[Day of Week] <>6 -- retira 2 ltimos dias da semana para pegar o mesmo perodo da semana atual",
              "    )",
              ")",
              ")"
            ],
            "lineageTag": "606f80b5-38fa-4f02-ad0d-9af179a55a7b"
          },
          {
            "name": "Check SLA (week)",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "IF(",
              "    [% SLA Achiev This/Last (Week)] >0,",
              "    \"Increased\",",
              "    \"Decreased\")"
            ],
            "lineageTag": "6d4510a9-a583-4887-a4c0-225bf3b157ad"
          },
          {
            "name": "Check MTTR (week)",
            "expression": [
              "",
              "VAR mttr_diff = [MTTR this week - Decimal] - [MTTR last week - Decimal]",
              "RETURN",
              "IF(",
              "    mttr_diff >0,",
              "    \"Increased\",",
              "    \"Decreased\")"
            ],
            "lineageTag": "609bc718-f27f-422a-b2f7-609e937d0617"
          },
          {
            "name": "Tickets Not Breached",
            "displayFolder": "SLA Breached",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(F_main[ticket_number]),",
              "    'F_main'[sla_breached_internal] <1,",
              "    USERELATIONSHIP(dCalendar[Data],F_main[resolved_at_formated]))"
            ],
            "formatString": "0",
            "lineageTag": "76c1fb60-1e54-4e18-9a87-df48fa72d609"
          },
          {
            "name": "Remains Open (backlog) L1",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(F_main[ticket_number]),",
              "    'F_main'[state_name] <> \"Closed\" && 'F_main'[state_name] <> \"Resolved\",",
              "    'F_main'[assignment_groups_list.level] = \"L1\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b7a3fbb2-584e-40f7-86c7-b1a2be428246"
          },
          {
            "name": "Remains Open (backlog) L2",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(F_main[ticket_number]),",
              "    'F_main'[state_name] <> \"Closed\" && 'F_main'[state_name] <> \"Resolved\",",
              "    'F_main'[assignment_groups_list.level] = \"L2\"",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "cd15e731-2b9b-4db1-87b6-83275e78810e"
          },
          {
            "name": "Closed Tickets",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "CALCULATE(",
              "    [Opened Tickets],",
              "    USERELATIONSHIP(dCalendar[Data],F_main[closed_at_formated]))"
            ],
            "formatString": "0",
            "lineageTag": "a38ae597-2953-4cb9-a7b5-ce7f7b30e7f3"
          },
          {
            "name": "L1 Retention",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE([Resolved Tickets],",
              "    'F_main'[last_assignment_group_level_inc] = \"L2\" &&",
              "    'F_main'[first_assignment_group_level_inc] = \"L1\"",
              "    ),",
              "    CALCULATE([Resolved Tickets],",
              "    'F_main'[first_assignment_group_level_inc] = \"L1\"",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8a1bda28-3cee-4074-82be-4369e3244334"
          },
          {
            "name": "Opened L1 Resolv L2",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "CALCULATE([Resolved Tickets],",
              "    'F_main'[last_assignment_group_level_inc] = \"L2\" &&",
              "    'F_main'[first_assignment_group_level_inc] = \"L1\"",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "58ab4676-5df8-4f21-a361-73dce09ab177"
          },
          {
            "name": "Opened L1",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "CALCULATE([Resolved Tickets],",
              "    'F_main'[first_assignment_group_level_inc] = \"L1\"",
              "    &&",
              "    ('F_main'[last_assignment_group_level_inc] = \"L2\" || 'F_main'[last_assignment_group_level_inc] = \"L1\")",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "2976d408-9bff-40af-91e5-eef7ec5ef7a1"
          },
          {
            "name": "Opened L1 Resolv L1",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "CALCULATE([Resolved Tickets],",
              "    'F_main'[last_assignment_group_level_inc] = \"L1\" &&",
              "    'F_main'[first_assignment_group_level_inc] = \"L1\"",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "dc6b4b68-3905-4abc-9e9d-0546cfdf2f53"
          },
          {
            "name": "Closed L1 OTC India",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "CALCULATE([Resolved Tickets],",
              "    'F_main'[first_assignment_group_inc] = \"APAC India APIN S4H OTC L1\"",
              "    &&",
              "    'F_main'[assignment_group] = \"GL Ops IND S4 OTC L2\"",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "3ddfc7bf-91c2-4b5d-af5e-0e89da0cbcb9"
          },
          {
            "name": "Opened L1 OTC India",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "CALCULATE([Resolved Tickets],",
              "    'F_main'[first_assignment_group_inc] = \"APAC India APIN S4H OTC L1\"",
              "    &&",
              "    ('F_main'[assignment_group] = \"GL Ops IND S4 OTC L2\" || 'F_main'[assignment_group] =\"APAC India APIN S4H OTC L1\")",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "32377c7c-6a00-401d-b982-2d3524d44945"
          },
          {
            "name": "L1 Retention - OTC (India)",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE([Resolved Tickets],",
              "    'F_main'[first_assignment_group_inc] = \"APAC India APIN S4H OTC L1\"",
              "    &&",
              "    'F_main'[assignment_group] = \"GL Ops IND S4 OTC L2\"",
              "    ),",
              "    CALCULATE([Resolved Tickets],",
              "    'F_main'[first_assignment_group_inc] = \"APAC India APIN S4H OTC L1\"",
              "    &&",
              "    ('F_main'[assignment_group] = \"GL Ops IND S4 OTC L2\" || 'F_main'[assignment_group] =\"APAC India APIN S4H OTC L1\")",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "191c708d-607e-42a6-9265-eb618fa5d569"
          },
          {
            "name": "L1 Retention - PTP (India)",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE([Resolved Tickets],",
              "    'F_main'[first_assignment_group_inc] = \"APAC India APIN S4H PTP L1\"",
              "    &&",
              "    'F_main'[assignment_group] = \"GL Ops IND S4 PTP L2\"",
              "    ),",
              "    CALCULATE([Resolved Tickets],",
              "    'F_main'[first_assignment_group_inc] = \"APAC India APIN S4H PTP L1\"",
              "    &&",
              "    ('F_main'[assignment_group] = \"GL Ops IND S4 PTP L2\" || 'F_main'[assignment_group] =\"APAC India APIN S4H PTP L1\")",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5ced9b72-92ca-4d45-a11c-9b16a24a0c7f"
          },
          {
            "name": "L1 Retention - Log/Supply (India)",
            "displayFolder": "Volume of Tickets",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE([Resolved Tickets],",
              "    ('F_main'[first_assignment_group_inc] = \"APAC India APIN S4H LOG L1\" || 'F_main'[first_assignment_group_inc] = \"APAC India APIN S4H SUP L1\")",
              "    &&",
              "    ('F_main'[assignment_group] = \"GL Ops IND S4 SUP L2\" || 'F_main'[assignment_group] = \"GL Ops IND S4 LOG L2\")",
              "    ),",
              "    CALCULATE([Resolved Tickets],",
              "    ('F_main'[first_assignment_group_inc] = \"APAC India APIN S4H LOG L1\" || 'F_main'[first_assignment_group_inc] = \"APAC India APIN S4H SUP L1\")",
              "    &&",
              "    ('F_main'[assignment_group] = \"GL Ops IND S4 SUP L2\" || 'F_main'[assignment_group] = \"GL Ops IND S4 LOG L2\" || 'F_main'[assignment_group] = \"APAC India APIN S4H SUP L1\" || 'F_main'[assignment_group] = \"APAC India APIN S4H LOG L1\")",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "66ea8a4a-c12e-4abb-bf83-5acd714c2098"
          }
        ],
        "partitions": [
          {
            "name": "Measure",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8076398f-91da-4551-a741-deff7f81740b",
            "sourceColumn": "Data",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_72c50f6a-e7cb-4a53-a5fa-5ecc7c7655c4"
                },
                "isDefault": true,
                "relationship": "b38a4e8c-9194-49b6-8170-c7e6666fffff"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "518f12b9-7e5f-45d4-9d41-f64542317206",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ebc04020-583a-42e9-a341-37d121d3ef12",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "3805924c-b4c2-40cb-899e-90763096cb97",
            "sortByColumn": "Month",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "507127d6-b9c2-4858-acbb-d41ab70c03d7",
            "sourceColumn": "Quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Week of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a558c37a-9ee4-48fe-a29b-4a498fe92425",
            "sourceColumn": "Week of Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Week of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0c0a826c-0bc2-40e5-ae34-0b4528c6acc2",
            "sourceColumn": "Week of Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b4defc38-91b0-420a-be0f-32a2be9e2069",
            "sourceColumn": "Day of Week",
            "summarizeBy": "sum"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "19ead6bb-b8bb-4a3b-821c-e3a0618b3800",
            "sortByColumn": "Day of Week",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          },
          {
            "name": "Check_Relative Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": [
              "",
              "VAR last_ticket = MAX('F_main'[opened_at_formated])",
              "VAR Last_ticket_prev_month = EDATE(last_ticket,-1)",
              "RETURN",
              "dCalendar[Data]<=Last_ticket_prev_month"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "lineageTag": "13341690-a8ac-4e61-b70d-26ff81f6058d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Check Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF(",
              "    DAY(dCalendar[Data])<8, \"1st Week\",",
              "    IF(DAY(dCalendar[Data])>7 && DAY(dCalendar[Data])<15,\"2nd Week\",",
              "    IF(DAY(dCalendar[Data])>14 && DAY(dCalendar[Data])<22,\"3rd Week\",",
              "    IF(DAY(dCalendar[Data])>21 && DAY(dCalendar[Data])<29,\"4th Week\",\"5th Week\"))))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "fce5a2a6-1032-4472-ba71-b75983d37a89",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month Name - Abrev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "LEFT(dCalendar[Month Name],3)",
            "isDataTypeInferred": true,
            "lineageTag": "51bb35d6-5963-4451-bbe8-a950450c0056",
            "sortByColumn": "Month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week/Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE([Check Week], \"-\")&[Month Name - Abrev]",
            "isDataTypeInferred": true,
            "lineageTag": "0f34642e-7d17-4fa2-90d2-eefadffd3d09",
            "sortByColumn": "Month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month/Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "[Month Name - Abrev] & \"/\" & [Year]",
            "isDataTypeInferred": true,
            "lineageTag": "2443e134-1616-4b6f-9288-8103ebf947e9",
            "sortByColumn": "Order month_year",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Bimester",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF([Month]<3,\"1st Bi\",",
              "IF([Month]<5,\"2nd Bi\",",
              "IF([Month]<7,\"3rd Bi\",",
              "IF([Month]<9,\"4th Bi\",",
              "IF([Month]<11,\"5th Bi\",",
              "\"6th Bi\"",
              ")))))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "66a3b69d-8808-4d04-83a2-88a06d80f6f7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Order month_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "CONCATENATE([Year],[Month])"
            ],
            "formatString": "0",
            "lineageTag": "6463ffb6-d15d-4aad-81f0-b8010bf96caf",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Order_Qtr/Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "CONCATENATE([Year],[Quarter])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "1f5aac48-7fe6-43b6-a3b2-cc50764d61de",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Qrt/Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Qtr \" & [Quarter] & \"/\" & [Year]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2ff35fd8-2d03-4673-8178-f2bf37896dec",
            "sortByColumn": "Order_Qtr/Year",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Bimester - Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "IF([Month]<3,1,",
              "IF([Month]<5,2,",
              "IF([Month]<7,3,",
              "IF([Month]<9,4,",
              "IF([Month]<11,5,",
              "6",
              ")))))"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a80f51d9-7941-4f7c-9608-42f0d6fdb70e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Order_Bi/Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "[Year] & [Bimester - Number]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "20848e2d-c36f-4a4f-b800-e3002170b61a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Year Hierarchy",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4e21337e-2182-49ad-9f7b-acce976a6ab8",
                "ordinal": 0
              },
              {
                "name": "Month/Year",
                "column": "Month/Year",
                "lineageTag": "11739c8b-af1f-4a87-b00c-129154126cf3",
                "ordinal": 1
              }
            ],
            "lineageTag": "398c114c-965a-44ab-8f89-63e9d04ba871"
          }
        ],
        "lineageTag": "b4d857c3-31d9-408e-aeee-5056e1f8cee5",
        "partitions": [
          {
            "name": "dCalendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = let",
                "    // Definir a data de incio do calendrio",
                "    DataInicio = #date(2024, 1, 1),",
                "",
                "    // Obter a data mxima da coluna 'Closed - Date' na tabela 'metrics'",
                "    DataFim = Date.From(List.Max(F_main[opened_at_formated])),",
                "",
                "    // Gerar uma lista de datas entre DataInicio e DataFim",
                "    ListaDatas = List.Dates(DataInicio, Duration.Days(DataFim - DataInicio) + 1, #duration(1, 0, 0, 0)),",
                "",
                "    // Converter a lista de datas em uma tabela",
                "    TabelaDatas = Table.FromList(ListaDatas, Splitter.SplitByNothing(), {\"Data\"}, null, ExtraValues.Error)",
                "in",
                "    TabelaDatas,",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Data\", type date}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Changed Type\", \"Year\", each Date.Year([Data]), Int64.Type),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Inserted Year\", \"Month\", each Date.Month([Data]), Int64.Type),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Inserted Month\", \"Month Name\", each Date.MonthName([Data]), type text),",
                "    #\"Inserted Quarter\" = Table.AddColumn(#\"Inserted Month Name\", \"Quarter\", each Date.QuarterOfYear([Data]), Int64.Type),",
                "    #\"Inserted Week of Year\" = Table.AddColumn(#\"Inserted Quarter\", \"Week of Year\", each Date.WeekOfYear([Data]), Int64.Type),",
                "    #\"Inserted Week of Month\" = Table.AddColumn(#\"Inserted Week of Year\", \"Week of Month\", each Date.WeekOfMonth([Data]), Int64.Type),",
                "    #\"Inserted Day of Week\" = Table.AddColumn(#\"Inserted Week of Month\", \"Day of Week\", each Date.DayOfWeek([Data]), Int64.Type),",
                "    #\"Inserted Day Name\" = Table.AddColumn(#\"Inserted Day of Week\", \"Day Name\", each Date.DayOfWeekName([Data]), type text)",
                "in",
                "    #\"Inserted Day Name\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_72c50f6a-e7cb-4a53-a5fa-5ecc7c7655c4",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "abff5027-bf03-4dda-be16-d136112d92ba",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "acce34f2-c756-4a5e-b476-1369962704f7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a1698c28-db10-4dd1-b104-419bfbabe057",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0b74e8f7-b470-41b0-a7ac-eaa5c3a6408f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7ad20d01-59bd-4227-ab12-b2952769ceec",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c39f540f-3ca6-4525-96b3-c082c57c64e9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "e9d66720-3186-4247-afa0-246154a1aed6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "91e6d715-f28d-49a6-ac44-87a949699969",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6fe35d75-69e0-461e-bb4c-599f47010954",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9b8446ba-06ee-4392-a57a-1d4eba99c723",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "24dc2f0e-b0da-4601-a713-2e8b7d969ebc",
                "ordinal": 3
              }
            ],
            "lineageTag": "f8daddbb-2954-41eb-a98c-169870bfe178"
          }
        ],
        "isHidden": true,
        "lineageTag": "0a20b80e-86c3-4816-92c9-b0b7c88e4f28",
        "partitions": [
          {
            "name": "LocalDateTable_72c50f6a-e7cb-4a53-a5fa-5ecc7c7655c4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dCalendar'[Data])), 1, 1), Date(Year(MAX('dCalendar'[Data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "TopN",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "609bc9760f884bacbd481e8ebb7b44e0"
          }
        ],
        "columns": [
          {
            "name": "TopN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "64f675b0-5e04-4b76-b4d4-fc3915d33e6d",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "316c4d91-1308-4d1e-a212-696b5214e865",
        "measures": [
          {
            "name": "TopN Value",
            "expression": "SELECTEDVALUE('TopN'[TopN], 1)",
            "formatString": "0",
            "lineageTag": "a4e6f7ca-3232-4fea-9be8-27576f478a69"
          }
        ],
        "partitions": [
          {
            "name": "TopN",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1, 15, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Macro Tema",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6ef889f667d946b7b586c1622ee743c8"
          }
        ],
        "columns": [
          {
            "name": "Macro Tema",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "a524c0cb-8747-475c-8113-58a7d9c5325c",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Macro Tema Fields"
                }
              ]
            },
            "sortByColumn": "Macro Tema Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Macro Tema Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "e9630e80-1a6c-47ad-9cb2-fafbf67bc01c",
            "sortByColumn": "Macro Tema Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Macro Tema Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "abfffc22-2d83-45ef-bf82-7a2f07fa1178",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "7d96c045-867a-4f28-b4c0-898ceaad2a38",
        "partitions": [
          {
            "name": "Macro Tema",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Category\", NAMEOF('metric'[Category]), 0),",
                "    (\"Skill\", NAMEOF('metric'[Skill]), 1),",
                "    (\"Resource Name\", NAMEOF('metric'[Resource Name]), 2),",
                "    (\"Affected Site\", NAMEOF('metric'[Affected Site]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cb4a0df047d74c0f9df9fd02a6e21a2f"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "5d310fb0-17d1-4fd2-b033-d6f33b80810f",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "18215d50-c75e-4766-9505-5f9b07499606",
        "measures": [
          {
            "name": "Parameter Value",
            "expression": "SELECTEDVALUE('Parameter'[Parameter], 1)",
            "formatString": "0",
            "lineageTag": "b7db5e06-b405-45c1-83fe-78a663cc69ae"
          }
        ],
        "partitions": [
          {
            "name": "Parameter",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 1, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Parameter 2",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7b68592badfa412a8a8f4b790c1ace99"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "0cc05435-38a2-4d7a-b560-e037c3938788",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "f913bb8f-29b9-4a53-9223-54671706ed36",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "703e90ef-f126-4c8a-8ac1-fa7fbf353c22",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "b1ce9aeb-c045-4ae7-8c0a-1a316af8e319",
        "partitions": [
          {
            "name": "Parameter 2",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Resource Name\", NAMEOF('metric'[Resource Name]), 0),",
                "    (\"Contractor\", NAMEOF('metric'[Company]), 1),",
                "    (\"Sub Cause\", NAMEOF('metric'[Sub Cause]), 2)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "assignment_groups_list",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3c3694b-9ac4-4e53-b24f-b35a9e951276",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "sys_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "248037f4-d325-46a1-977c-12db9defbc24",
            "sourceColumn": "sys_id",
            "summarizeBy": "none"
          },
          {
            "name": "title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afa9c9d2-e04c-4f34-ba2b-93f47921e22e",
            "sourceColumn": "title",
            "summarizeBy": "none"
          },
          {
            "name": "zone_country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e6fdf36-1516-41c3-a2aa-4b4faf9dbdf1",
            "sourceColumn": "zone_country",
            "summarizeBy": "none"
          },
          {
            "name": "ag_project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f1b7a3a-37de-403a-b2e5-e65887ca0866",
            "sourceColumn": "ag_project",
            "summarizeBy": "none"
          },
          {
            "name": "path",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a181cf81-457c-46af-a6ca-d119e3d6403e",
            "sourceColumn": "path",
            "summarizeBy": "none"
          },
          {
            "name": "level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e02ea7ad-9d8a-4f9e-b5b8-a56a36466874",
            "sourceColumn": "level",
            "summarizeBy": "none"
          },
          {
            "name": "workstream",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "958c1601-3a5b-42e6-93a5-a7484f61d922",
            "sourceColumn": "workstream",
            "summarizeBy": "none"
          },
          {
            "name": "ag_tower",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2c9dbc0-e72a-4c43-8782-a9b154e80670",
            "sourceColumn": "ag_tower",
            "summarizeBy": "none"
          },
          {
            "name": "metrics_value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3a7da1d-0155-442d-b6f5-2819557dbc1e",
            "sourceColumn": "metrics_value",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6d1b3149-50ea-4e87-b8c8-ca37a639c8f7",
        "partitions": [
          {
            "name": "assignment_groups_list",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(\"https://hyperautoadlsanlprod.dfs.core.windows.net/gold/parameters/internal_assignment_groups_list\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Extension] = \".parquet\")),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(#\"Filtered Rows\", each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File (4)\", each #\"Transform File (4)\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File (4)\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (4)\", Table.ColumnNames(#\"Transform File (4)\"(#\"Sample File (4)\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"sys_id\", type text}, {\"title\", type text}, {\"zone_country\", type text}, {\"ag_project\", type text}, {\"path\", type text}, {\"level\", type text}, {\"workstream\", type text}, {\"ag_tower\", type text}}),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Changed Type\", each ([level] = \"L1\" or [level] = \"L2\") and ([workstream] <> \"HYPERCARE\" and [workstream] <> \"NON SAP\" and [workstream] <> \"UAM\"))",
                "in",
                "    #\"Filtered Rows2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "analyst_list",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51e9a129-25a7-41d3-a02d-3eea77131bf3",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "snow_email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54bab34a-05c5-47b6-b656-991183ea4f96",
            "sourceColumn": "snow_email",
            "summarizeBy": "none"
          },
          {
            "name": "display_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9b6b4c0-ed87-4346-8f19-883f019d47d1",
            "sourceColumn": "display_name",
            "summarizeBy": "none"
          },
          {
            "name": "scope",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d3d8367-24e9-4731-a1ee-596e3c316d94",
            "sourceColumn": "scope",
            "summarizeBy": "none"
          },
          {
            "name": "skill",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2ad6b65-e949-4fc5-b67e-1eae3ea2d8a9",
            "sourceColumn": "skill",
            "summarizeBy": "none"
          },
          {
            "name": "location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75d48fa7-776c-410c-bb2a-7ff791d2fe43",
            "sourceColumn": "location",
            "summarizeBy": "none"
          },
          {
            "name": "tower_lead",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f64ec04-576f-428a-99b0-21794c98cb19",
            "sourceColumn": "tower_lead",
            "summarizeBy": "none"
          },
          {
            "name": "company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8363473-95e2-4662-8527-b34aa0011312",
            "sourceColumn": "company",
            "summarizeBy": "none"
          },
          {
            "name": "level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a17fe801-eea2-4b7f-bada-c0cb056ffbfb",
            "sourceColumn": "level",
            "summarizeBy": "none"
          },
          {
            "name": "sys_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "882135e7-7313-4017-a984-c9166b167c7f",
            "sourceColumn": "sys_id",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15ddc3b7-5ab0-4761-8dc3-171372e54df1",
            "sourceColumn": "status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d2751936-711e-45d0-b28f-a3e767ce0903",
        "partitions": [
          {
            "name": "analyst_list",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(\"https://hyperautoadlsanlprod.dfs.core.windows.net/gold/parameters/internal_analyst_list\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Extension] = \".parquet\")),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(#\"Filtered Rows\", each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File (8)\", each #\"Transform File (8)\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File (8)\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (8)\", Table.ColumnNames(#\"Transform File (8)\"(#\"Sample File (8)\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"snow_email\", type text}, {\"display_name\", type text}, {\"scope\", type text}, {\"skill\", type text}, {\"location\", type text}, {\"tower_lead\", type text}, {\"company\", type text}, {\"level\", type text}, {\"sys_id\", type text}, {\"status\", type text}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\", {\"sys_id\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "F_main",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8807077e-934f-4fdc-b5ce-ab909badcb2e",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "ticket_sys_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb7d98e5-7f76-4087-8e41-d1822b0e9bce",
            "sourceColumn": "ticket_sys_id",
            "summarizeBy": "none"
          },
          {
            "name": "ticket_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f5f9473-23d8-4d6f-bc8f-64ee0d4ad008",
            "sourceColumn": "ticket_number",
            "summarizeBy": "none"
          },
          {
            "name": "opened_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ccd1d679-5c82-46dc-bf6a-1385f4a3bd82",
            "sourceColumn": "opened_at",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2f6c9ccd-1390-4791-9967-d365da8e8579"
                },
                "isDefault": true,
                "relationship": "eb981103-134e-4908-8bf9-96b687d87df4"
              }
            ]
          },
          {
            "name": "opened_at_formated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "edddb5e2-2df5-4c79-bbe3-9a1be5fd7409",
            "sourceColumn": "opened_at_formated",
            "summarizeBy": "none"
          },
          {
            "name": "resolved_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d62d5331-4e10-4c68-928f-01f2982ff70f",
            "sourceColumn": "resolved_at",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_81c838cd-46d2-4463-91c0-f6ee98a86607"
                },
                "isDefault": true,
                "relationship": "fd25827f-281d-4ac6-9c42-f9794f044c0e"
              }
            ]
          },
          {
            "name": "resolved_at_formated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "fd5e0f39-dee2-4340-bf2e-8bec7fbfacd2",
            "sourceColumn": "resolved_at_formated",
            "summarizeBy": "none"
          },
          {
            "name": "closed_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4720a76d-3c80-4e80-88e2-99f8f89ad628",
            "sourceColumn": "closed_at",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_15fca2cf-8a52-4f21-bcee-9c358a8334bf"
                },
                "isDefault": true,
                "relationship": "a02935db-7267-4f41-b35a-619651e74328"
              }
            ]
          },
          {
            "name": "closed_at_formated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "09aa1444-7706-431f-b258-4dd095601ca2",
            "sourceColumn": "closed_at_formated",
            "summarizeBy": "none"
          },
          {
            "name": "priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "466d835a-c12a-4662-937d-0324e47ea74e",
            "sourceColumn": "priority",
            "summarizeBy": "sum"
          },
          {
            "name": "assignment_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82be89b3-8f53-4aaf-9d53-29f106f368f2",
            "sourceColumn": "assignment_group",
            "summarizeBy": "none"
          },
          {
            "name": "assignment_group_sys_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d718a875-e7ca-42e1-a443-477d277ffffd",
            "sourceColumn": "assignment_group_sys_id",
            "summarizeBy": "none"
          },
          {
            "name": "assigned_to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f73fbb94-8449-48ec-b00b-7c93789a7c76",
            "sourceColumn": "assigned_to",
            "summarizeBy": "none"
          },
          {
            "name": "assigned_to_sys_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d051f80-bd82-4209-84ee-e63adfd51c80",
            "sourceColumn": "assigned_to_sys_id",
            "summarizeBy": "none"
          },
          {
            "name": "business_service",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea20ea4f-b7a8-41d1-9634-f89f47e086a4",
            "sourceColumn": "business_service",
            "summarizeBy": "none"
          },
          {
            "name": "opened_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ece73e4a-6bae-4df5-8670-11b06873478f",
            "sourceColumn": "opened_by",
            "summarizeBy": "none"
          },
          {
            "name": "close_notes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "907853ac-aeb4-4c10-8337-a6022be094fc",
            "sourceColumn": "close_notes",
            "summarizeBy": "none"
          },
          {
            "name": "mttr_in_seconds",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f3a098b-87f5-4156-a466-82c704f3d596",
            "sourceColumn": "mttr_in_seconds",
            "summarizeBy": "sum"
          },
          {
            "name": "state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "edea9d82-e02c-4dd8-af72-e2c5d7bca4ee",
            "sourceColumn": "state",
            "summarizeBy": "sum"
          },
          {
            "name": "state_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77972496-b70f-4b3d-96b4-a8157a0ae040",
            "sourceColumn": "state_group",
            "summarizeBy": "none"
          },
          {
            "name": "csat_avaliation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0962ce70-3a3a-4a2c-a247-207ffa0ed2d9",
            "sourceColumn": "csat_avaliation",
            "summarizeBy": "none"
          },
          {
            "name": "row_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6760ac6-a661-4a93-b230-58ef4071e13b",
            "sourceColumn": "row_type",
            "summarizeBy": "none"
          },
          {
            "name": "priority_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adba0f9d-488b-4543-8e5a-e987d9ee35c0",
            "sourceColumn": "priority_name",
            "summarizeBy": "none"
          },
          {
            "name": "state_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aef62f0f-06ab-4f24-91d1-aacb4b9d9899",
            "sourceColumn": "state_name",
            "summarizeBy": "none"
          },
          {
            "name": "parent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e048cae-ec78-44f0-8dce-5ea4d63e7860",
            "sourceColumn": "parent",
            "summarizeBy": "none"
          },
          {
            "name": "description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6894b841-2a90-4821-bb66-f420b40c6301",
            "sourceColumn": "description",
            "summarizeBy": "none"
          },
          {
            "name": "short_description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "582b8636-35e9-4d3b-ab7c-0d9a184aa018",
            "sourceColumn": "short_description",
            "summarizeBy": "none"
          },
          {
            "name": "sla_breached",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d7166f45-e315-47e4-be23-01a8a6f224fa",
            "sourceColumn": "sla_breached",
            "summarizeBy": "sum"
          },
          {
            "name": "sla_total_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aa5dc30b-9844-4796-b261-adaae1e91465",
            "sourceColumn": "sla_total_count",
            "summarizeBy": "sum"
          },
          {
            "name": "sla_breached_internal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "834c4820-af7c-42c4-b8cd-fa6ec0912c84",
            "sourceColumn": "sla_breached_internal",
            "summarizeBy": "sum"
          },
          {
            "name": "sla_internal_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5a3e41de-120c-4bd9-b7fb-ca76669de7bb",
            "sourceColumn": "sla_internal_count",
            "summarizeBy": "sum"
          },
          {
            "name": "ola_breached",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5cae28c-206f-4f5c-bf8c-efae0ab13f4c",
            "sourceColumn": "ola_breached",
            "summarizeBy": "none"
          },
          {
            "name": "ola_total_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b4183f2-177f-4857-b477-9b1e31650b51",
            "sourceColumn": "ola_total_count",
            "summarizeBy": "none"
          },
          {
            "name": "ola_breached_internal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3858d8ff-8e2e-4b92-9f3e-44db52c2d528",
            "sourceColumn": "ola_breached_internal",
            "summarizeBy": "none"
          },
          {
            "name": "ola_internal_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2bc637e-6ecb-4f7a-8e64-8b86a9f5e5e0",
            "sourceColumn": "ola_internal_count",
            "summarizeBy": "none"
          },
          {
            "name": "sys_updated_on_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5becb2e9-f881-42bc-8441-8d018920cf10",
            "sourceColumn": "sys_updated_on_inc",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_640ae0a0-c358-482d-be4b-aaee15fb27e9"
                },
                "isDefault": true,
                "relationship": "a5dc6bd2-8ee8-4584-80c0-7d001ff15c96"
              }
            ]
          },
          {
            "name": "sys_updated_on_formated_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f36658e6-fc39-4047-8abb-6abb8173cda9",
            "sourceColumn": "sys_updated_on_formated_inc",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ff4037a4-71bd-4c0f-9e70-eda722c4953b"
                },
                "isDefault": true,
                "relationship": "ff765e2a-2243-4313-b8ca-a573d152e3e2"
              }
            ]
          },
          {
            "name": "sub_category_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5d45f21-e0de-4ad7-9cfa-13cf1692070a",
            "sourceColumn": "sub_category_inc",
            "summarizeBy": "none"
          },
          {
            "name": "resolved_by_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c90daf08-5c67-4ef6-ade8-5eacabb3a6e9",
            "sourceColumn": "resolved_by_inc",
            "summarizeBy": "none"
          },
          {
            "name": "resolved_by_sys_id_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8897f17-020e-4cac-962d-12696c63ba61",
            "sourceColumn": "resolved_by_sys_id_inc",
            "summarizeBy": "none"
          },
          {
            "name": "reassignment_count_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f32c361-e5d6-434d-b29f-ad2d2e1a4aa2",
            "sourceColumn": "reassignment_count_inc",
            "summarizeBy": "sum"
          },
          {
            "name": "reopen_count_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "376104f2-feb0-49cf-acd8-f41081d99ead",
            "sourceColumn": "reopen_count_inc",
            "summarizeBy": "sum"
          },
          {
            "name": "sub_cause_name_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4159027-a2b6-4653-8454-1ed1803c9832",
            "sourceColumn": "sub_cause_name_inc",
            "summarizeBy": "none"
          },
          {
            "name": "u_location_display_value_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d0d51f4-4a34-4e87-8677-a967fb164a95",
            "sourceColumn": "u_location_display_value_inc",
            "summarizeBy": "none"
          },
          {
            "name": "affected_site_display_value_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26d8b2e3-d6f0-4c8a-9d8f-bede13cfe40f",
            "sourceColumn": "affected_site_display_value_inc",
            "summarizeBy": "none"
          },
          {
            "name": "affected_location_saz_display_value_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "acbe9364-a0f0-450b-87d4-3f745844f7c8",
            "sourceColumn": "affected_location_saz_display_value_inc",
            "summarizeBy": "none"
          },
          {
            "name": "problem_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9cce110c-2c5c-430c-bb97-f7c682085295",
            "sourceColumn": "problem_inc",
            "summarizeBy": "none"
          },
          {
            "name": "problem_sys_id_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa6b7c38-5f94-48eb-a90a-a5d4f489d3ac",
            "sourceColumn": "problem_sys_id_inc",
            "summarizeBy": "none"
          },
          {
            "name": "is_monitoring_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "28508a89-72a7-4c99-9d77-1f247c52d45c",
            "sourceColumn": "is_monitoring_inc",
            "summarizeBy": "none"
          },
          {
            "name": "first_assigned_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48a6c7bb-c78d-4b7b-9a88-6b71112eb1f2",
            "sourceColumn": "first_assigned_inc",
            "summarizeBy": "none"
          },
          {
            "name": "mtta_in_seconds_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1639c400-7d1e-4c21-bc21-6c373d595d83",
            "sourceColumn": "mtta_in_seconds_inc",
            "summarizeBy": "none"
          },
          {
            "name": "first_assignment_group_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfa6c98a-23b4-41db-848b-26b3e689a865",
            "sourceColumn": "first_assignment_group_inc",
            "summarizeBy": "none"
          },
          {
            "name": "first_assignment_group_level_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4015cf6-c62f-41c8-9e46-e60710a10706",
            "sourceColumn": "first_assignment_group_level_inc",
            "summarizeBy": "none"
          },
          {
            "name": "last_assignment_group_level_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25789928-f728-4ecb-877c-b8f9111676db",
            "sourceColumn": "last_assignment_group_level_inc",
            "summarizeBy": "none"
          },
          {
            "name": "frt_in_seconds_inc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "400f9f17-41a0-415d-9b4a-acd5682d0395",
            "sourceColumn": "frt_in_seconds_inc",
            "summarizeBy": "sum"
          },
          {
            "name": "configuration_item_req",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a76cae8-2902-43fa-8a7a-0e00bf53a752",
            "sourceColumn": "configuration_item_req",
            "summarizeBy": "none"
          },
          {
            "name": "location_req",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0b6fa83-2cff-4bf3-8c3d-11b97b252f61",
            "sourceColumn": "location_req",
            "summarizeBy": "none"
          },
          {
            "name": "select_the_environment_req",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ba07da2-7b99-4ef6-83ec-02c079fc17d2",
            "sourceColumn": "select_the_environment_req",
            "summarizeBy": "none"
          },
          {
            "name": "whats_your_plant_req",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d6c3005-8d8e-4ab3-8bdb-4416442bdbf9",
            "sourceColumn": "whats_your_plant_req",
            "summarizeBy": "none"
          },
          {
            "name": "stage_display_value_req",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c9e4656-bc06-4f40-9ae1-ef065abd487c",
            "sourceColumn": "stage_display_value_req",
            "summarizeBy": "none"
          },
          {
            "name": "approval_req",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8e6afba-5a1e-4aa5-8108-d8b3eb448804",
            "sourceColumn": "approval_req",
            "summarizeBy": "none"
          },
          {
            "name": "u_location_req",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28732dfc-e733-4b49-b79d-9ba5677c7666",
            "sourceColumn": "u_location_req",
            "summarizeBy": "none"
          },
          {
            "name": "assignment_groups_list.title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ffad6ed-4ae0-41e1-a6e0-c3272d153f01",
            "sourceColumn": "assignment_groups_list.title",
            "summarizeBy": "none"
          },
          {
            "name": "assignment_groups_list.level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5845f48-1954-4be7-b34c-71f9c40658b1",
            "sourceColumn": "assignment_groups_list.level",
            "summarizeBy": "none"
          },
          {
            "name": "assignment_groups_list.workstream",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9fe0d3a9-62c9-4f67-8c10-e902fa2f56c3",
            "sourceColumn": "assignment_groups_list.workstream",
            "summarizeBy": "none"
          },
          {
            "name": "analyst_list.skill",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b112b179-8f8f-43d7-aa36-621cf8966424",
            "sourceColumn": "analyst_list.skill",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Cause",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb69417f-3ced-4d46-8deb-6fd3468dbda7",
            "sourceColumn": "Sub Cause",
            "summarizeBy": "none"
          },
          {
            "name": "caller",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b3176e1-100d-47f3-914d-b309a176d2a1",
            "sourceColumn": "caller",
            "summarizeBy": "none"
          },
          {
            "name": "category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef9306df-619c-475d-b9d3-7d3580d5e8a0",
            "sourceColumn": "category",
            "summarizeBy": "none"
          },
          {
            "name": "assignment_groups_list.zone_country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cac187c5-617b-4c0f-8fb1-41fa04c49ee1",
            "sourceColumn": "assignment_groups_list.zone_country",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "82a120dc-64b2-4cfc-8f1d-9bb877e4f5c2",
        "partitions": [
          {
            "name": "F_main",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(\"https://hyperautoadlsanlprod.dfs.core.windows.net/gold/schemas/ams/main\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Extension] = \".parquet\")),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(#\"Filtered Rows\", each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File (6)\", each #\"Transform File (6)\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File (6)\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (6)\", Table.ColumnNames(#\"Transform File (6)\"(#\"Sample File (6)\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"ticket_sys_id\", type text}, {\"ticket_number\", type text}, {\"opened_at\", type datetime}, {\"opened_at_formated\", type date}, {\"resolved_at\", type datetime}, {\"resolved_at_formated\", type date}, {\"closed_at\", type datetime}, {\"closed_at_formated\", type date}, {\"priority\", Int64.Type}, {\"assignment_group\", type text}, {\"assignment_group_sys_id\", type text}, {\"assigned_to\", type text}, {\"assigned_to_sys_id\", type text}, {\"business_service\", type text}, {\"opened_by\", type text}, {\"close_notes\", type text}, {\"mttr_in_seconds\", Int64.Type}, {\"state\", Int64.Type}, {\"state_group\", type text}, {\"csat_avaliation\", type any}, {\"row_type\", type text}, {\"priority_name\", type text}, {\"state_name\", type text}, {\"parent\", type text}, {\"description\", type text}, {\"short_description\", type text}, {\"sla_breached\", type any}, {\"sla_total_count\", type any}, {\"sla_breached_internal\", type any}, {\"sla_internal_count\", type any}, {\"ola_breached\", type any}, {\"ola_total_count\", type any}, {\"ola_breached_internal\", type any}, {\"ola_internal_count\", type any}, {\"sys_updated_on_inc\", type datetime}, {\"sys_updated_on_formated_inc\", type date}, {\"category\", type text}, {\"sub_category_inc\", type text}, {\"resolved_by_inc\", type text}, {\"resolved_by_sys_id_inc\", type text}, {\"reassignment_count_inc\", Int64.Type}, {\"reopen_count_inc\", Int64.Type}, {\"sub_cause_name_inc\", type text}, {\"u_location_display_value_inc\", type text}, {\"affected_site_display_value_inc\", type text}, {\"affected_location_saz_display_value_inc\", type text}, {\"problem_inc\", type text}, {\"problem_sys_id_inc\", type text}, {\"is_monitoring_inc\", type logical}, {\"first_assigned_inc\", type any}, {\"mtta_in_seconds_inc\", type any}, {\"first_assignment_group_inc\", type any}, {\"first_assignment_group_level_inc\", type any}, {\"last_assignment_group_level_inc\", type any}, {\"frt_in_seconds_inc\", Int64.Type}, {\"configuration_item_req\", type any}, {\"location_req\", type any}, {\"select_the_environment_req\", type any}, {\"whats_your_plant_req\", type any}, {\"stage_display_value_req\", type any}, {\"approval_req\", type any}, {\"u_location_req\", type any}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"assignment_group_sys_id\"}, assignment_groups_list, {\"sys_id\"}, \"assignment_groups_list\", JoinKind.LeftOuter),",
                "    #\"Expanded assignment_groups_list\" = Table.ExpandTableColumn(#\"Merged Queries\", \"assignment_groups_list\", {\"title\", \"zone_country\", \"level\", \"workstream\"}, {\"assignment_groups_list.title\", \"assignment_groups_list.zone_country\", \"assignment_groups_list.level\", \"assignment_groups_list.workstream\"}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Expanded assignment_groups_list\", each ([assignment_groups_list.title] <> null)),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Filtered Rows1\",{{\"sla_breached\", Int64.Type}, {\"sla_total_count\", Int64.Type}, {\"sla_breached_internal\", Int64.Type}, {\"sla_internal_count\", Int64.Type}}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Changed Type1\", {\"assigned_to_sys_id\"}, analyst_list, {\"sys_id\"}, \"analyst_list\", JoinKind.LeftOuter),",
                "    #\"Expanded analyst_list\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"analyst_list\", {\"skill\"}, {\"analyst_list.skill\"}),",
                "    #\"Filtered Rows3\" = Table.SelectRows(#\"Expanded analyst_list\", each [opened_at_formated] > #date(2023, 12, 31)),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Filtered Rows3\", \"Sub Cause\", each if Text.Contains([sub_cause_name_inc], \"How\") then \"How To\" else [sub_cause_name_inc]),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Added Conditional Column\", each ([row_type] = \"incident\"))",
                "in",
                "    #\"Filtered Rows2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2f6c9ccd-1390-4791-9967-d365da8e8579",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8f3dc5b6-d413-407e-b0ef-87e8b2acdf11",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "81995a05-5c22-4693-ad04-ea4852e197a9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "d6096349-133d-47aa-b91e-50b45b9bccc6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "30dac391-64a5-4f88-a1a6-43284f076aa7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "4c4c5450-1515-4674-bb7a-42afa9989a67",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "fe62a252-e24e-47e9-91e7-3865398ae55f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "27f9bd33-6a2a-4655-a724-434a9ed277d0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2aecaa25-2120-471e-8a28-3834478ef1b3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "04546d60-d635-40f0-a227-4fc18c765814",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "158a5c47-2fe1-499f-bf5f-2b5540b19978",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "305da761-e743-4136-a92b-d1bad96cc084",
                "ordinal": 3
              }
            ],
            "lineageTag": "2b3040ab-2321-4ff0-9b78-2fc1abde5feb"
          }
        ],
        "isHidden": true,
        "lineageTag": "7ffe77e4-6cb7-447f-87f9-e31a38e623bf",
        "partitions": [
          {
            "name": "LocalDateTable_2f6c9ccd-1390-4791-9967-d365da8e8579",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('F_main'[opened_at])), 1, 1), Date(Year(MAX('F_main'[opened_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_81c838cd-46d2-4463-91c0-f6ee98a86607",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f05d2072-bf4f-4927-ac08-ab2a4abe0e78",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "5d069a86-133e-4624-af84-e882f0909dd1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "814f52b7-3d4f-4e1e-a7f4-64c996dc12d6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0f42f763-05d3-4ecb-820a-3c7c32ecd4e9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "461b9649-85c8-45e2-80c9-3bb249230cf8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "255c70d1-02fb-42bf-8552-2b5b9d367f66",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d73ad48d-4cd8-4c8b-9c4b-0518097f080b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5256b48d-3a7c-4894-8feb-3488afd062e1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c4166161-b484-42f4-a18a-4adfc3fb28b1",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8160fad1-c322-478d-908d-1f39db012314",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2a669334-0724-45d1-a8e4-da7cee0601e7",
                "ordinal": 3
              }
            ],
            "lineageTag": "ec724384-0661-49d4-ad33-2d194443d6f0"
          }
        ],
        "isHidden": true,
        "lineageTag": "90869b59-2b76-4882-ac9c-eeac66bd8bc3",
        "partitions": [
          {
            "name": "LocalDateTable_81c838cd-46d2-4463-91c0-f6ee98a86607",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('F_main'[resolved_at])), 1, 1), Date(Year(MAX('F_main'[resolved_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_15fca2cf-8a52-4f21-bcee-9c358a8334bf",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "62952b3b-f3da-414a-8cb4-1f92ad653cca",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "378c49e2-b83e-412f-af60-a69223e18aa4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5cc82347-1e8c-43e4-ad82-100feaa86b6c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "202ed7e4-109a-4f80-bf1b-96020a8ac2ad",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "596c6f15-4623-4042-b3bd-0eae56a1bfda",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f5755ce8-af66-46c0-83c4-bdb3265a2b78",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "c47ba65b-6816-4a3f-8773-a19b47186fd9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5712c903-51bd-4a56-b925-a1059b4aaaf4",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e52c3f49-1759-4985-916a-3663a166fdfb",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "da2e47ff-9c43-4bd9-bb0c-e7543f11de8f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ca79298e-9640-421f-8c91-49544522e40d",
                "ordinal": 3
              }
            ],
            "lineageTag": "d0dab113-09f3-4e48-aaa9-4c263c1bb371"
          }
        ],
        "isHidden": true,
        "lineageTag": "a150874f-d165-47ba-ad1d-3d73732b1fba",
        "partitions": [
          {
            "name": "LocalDateTable_15fca2cf-8a52-4f21-bcee-9c358a8334bf",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('F_main'[closed_at])), 1, 1), Date(Year(MAX('F_main'[closed_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_640ae0a0-c358-482d-be4b-aaee15fb27e9",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "dd67f722-7d3a-4a9e-96ba-708b3d937658",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "deedeac5-5dd4-4e00-b0dd-427b282e92ae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "eb44e44a-b554-431a-8573-ae998d9eabc0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "63417882-bcde-4fb2-85b4-d9ce2cdbe1e7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "9315040b-e79e-46e4-aaf6-d92fa0de38ed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5e3cc544-a764-4e9b-98a0-93c57930504e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8b1930fb-9fed-46bb-8547-7206aff81164",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ecf37033-7a88-41ca-b1d0-5c31234a8b9e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "87d31c46-fbaa-4309-8b03-e1d4a8602c83",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4fa62fa8-b5b4-4e6a-ba3b-2a7d49b2c427",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e88c9bbd-50b4-4275-979c-8e248f67c9a5",
                "ordinal": 3
              }
            ],
            "lineageTag": "75d3595a-0117-4bbe-9c53-3ac2444508a3"
          }
        ],
        "isHidden": true,
        "lineageTag": "98dd9060-5669-414d-8aab-de50b7500f50",
        "partitions": [
          {
            "name": "LocalDateTable_640ae0a0-c358-482d-be4b-aaee15fb27e9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('F_main'[sys_updated_on_inc])), 1, 1), Date(Year(MAX('F_main'[sys_updated_on_inc])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_ff4037a4-71bd-4c0f-9e70-eda722c4953b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8959d9ce-2e23-436b-9fd0-4d5f6486d92a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "37727fc8-9207-40c2-b0d7-79daa71b3641",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "fd4e8486-cc1b-4bc4-a15c-c5dd53e8f2c4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f507ba18-cde7-4211-af07-72f0a36b83e6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "ae87d5c7-766c-44e0-833d-7a7faec8dda1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e61ec015-646d-4d37-b932-4787cdd44253",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b992e175-6aec-441e-bca0-f63c899925da",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9eda418d-444c-43a6-8534-1a40192daf31",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8d9daaa5-244d-4d1d-811b-6fc12c3bac62",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bde63486-4fa3-4d50-bb3a-e3020697a3da",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "055967f5-2f07-4890-824b-34bc75b402ac",
                "ordinal": 3
              }
            ],
            "lineageTag": "5f72a24e-8232-4ba0-aa98-d934f61e19fc"
          }
        ],
        "isHidden": true,
        "lineageTag": "ebabcc5b-dbfe-4fa0-82af-71a691b67185",
        "partitions": [
          {
            "name": "LocalDateTable_ff4037a4-71bd-4c0f-9e70-eda722c4953b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('F_main'[sys_updated_on_formated_inc])), 1, 1), Date(Year(MAX('F_main'[sys_updated_on_formated_inc])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}